### ISSUE TITLE
Phalcon ZEPHIR mysterious error when call isPost

### ISSUE THREAD

**Issue by softdream** [phalcon/cphalcon#10363]
Hello i got this error: 

```
PHP Fatal error:  Uncaught exception 'BadMethodCallException' with message 'Wrong number of parameters' in /var/www/fairplayauto.cz/web/app/modules/WebModule/controller/RadceController.php:214\nStack trace:\n#0 [internal function]: Phalcon\\Http\\Response->setJsonContent()\n#1 /var/www/fairplayauto.cz/web/app/modules/WebModule/controller/RadceController.php(214): Phalcon\\Http\\Request->isPost()\n#2 [internal function]: Web\\Controller\\RadceController->ekonomikaAction()\n#3 [internal function]: Phalcon\\Dispatcher->dispatch()\n#4 /var/www/fairplayauto.cz/web/app/bootstrap.php(257): Phalcon\\Mvc\\Application->handle()\n#5 /var/www/fairplayauto.cz/web/public/index.php(56): require_once('/var/www/fairpl...')\n#6 {main}\n  thrown in /var/www/fairplayauto.cz/web/app/modules/WebModule/controller/RadceController.php on line 214, referer: https://fairplayauto.cz/radce/jizda/
```

On line where is the isPost:

```php
if($this->request->isPost()){ // <-- here is the line
            $data['desc'] = $this->request->getPost();
            if($form->isValid($this->request->getPost())){
                $car->car->fn_data = base64_encode(serialize($data));
                if($car->save()){
                    $d = unserialize(base64_decode($car->car->fn_data));
                    $this->response->redirect('auto/vybava/'.$car->car->id.'/');
                }
                else {
                    $this->flash->error('Omlouváme se něco se nepovedlo, opakujte akci prosím později.');
                    $this->response->redirect('auto/popis/'.$car->car->id.'/');
                }
            }

```

And i can't understant why it happens, because it happen just sometimes, this has happen when i had upgrade phalcon to zephir.

**Comment by SidRoberts** [comment]
Are you using `setJsonContent()` anywhere? The method requires at least one parameter: https://github.com/phalcon/cphalcon/blob/2.0.x/phalcon/http/response.zep#L502

**Comment by andresgutierrez** [comment]
What do you have in /var/www/fairplayauto.cz/web/app/modules/WebModule/controller/RadceController.php line 214?

**Comment by softdream** [comment]
andre: 
this one: 
``` 
if($this->request->isPost()){ // <-- here is the line

```

Roberts: no.

**Comment by andresgutierrez** [comment]
Are you using 2.0.1?

**Comment by Green-Cat** [comment]
@softdream Could you try again using phalcon 2.0.2?
