### ISSUE TITLE
ACL truncates access names to 16 characters

### ISSUE THREAD

**Issue by alec-w** [phalcon/cphalcon#10960]
When I add an action over 16 characters in length to the ACL it appears to be truncated to 16 characters.

If I have the following as part of my `privateResources`

    'users' => array(
            'index',
            'search',
            'edit',
            'create',
            'delete',
            'changePassword',
            'adminChangePassword'
    )

then I get the following error

    Access 'adminChangePassw' does not exist in resource 'users'
    #0 [internal function]: Phalcon\Acl\Adapter\Memory->_allowOrDeny('Administrators', 'users', 'adminChangePass...', 1)
    #1 C:\wamp\www\vokuro\app\library\Acl\Acl.php(201): Phalcon\Acl\Adapter\Memory->allow('Administrators', 'users', 'adminChangePass...')
    #2 C:\wamp\www\vokuro\app\controllers\PermissionsController.php(49): Vokuro\Acl\Acl->rebuild()
    #3 [internal function]: Vokuro\Controllers\PermissionsController->indexAction()
    #4 [internal function]: Phalcon\Dispatcher->dispatch()
    #5 C:\wamp\www\vokuro\public\index.php(33): Phalcon\Mvc\Application->handle()
    #6 {main}

I came across this issue in my current project, the above error code is from testing the same function in my working Vokuro example.

This appears to be a bug in `Phalcon\Acl\Adapter\Memory` but after examining the Zephir code I cannot see anything that I think would truncate the string passed.

**Comment by alec-w** [comment]
This is because I had been working from the Vokuro example code - the database for which limits the size of the action and resource fields to 16 characters. Changing the database setup to allow more characters in those fields fixes the problem.
