### ISSUE TITLE
 Fatal error: Uncaught exception 'Phalcon\Mvc\Model\Exception' with message 'Syntax error, 

### ISSUE THREAD

**Issue by emrullahayin** [phalcon/cphalcon#11064]
```
Fatal error: Uncaught exception 'Phalcon\Mvc\Model\Exception' with message

'Syntax error, unexpected token >, near to ' LIMIT :APL0:', when parsing:
  SELECT [Multiple\Backend\Models\urunler].*
  FROM [Multiple\Backend\Models\urunler] 
  WHERE urunNo => LIMIT :APL0: (111)'

in C:\xampp\htdocs\BestShop\apps\backend\models\urunler.php:42
Stack trace:
#0 [internal function]: Phalcon\Mvc\Model\Query->parse()
#1 [internal function]: Phalcon\Mvc\Model\Query->execute()
#2 C:\xampp\htdocs\BestShop\apps\backend\models\urunler.php(42): Phalcon\Mvc\Model::findFirst(Array)
#3 C:\xampp\htdocs\BestShop\apps\backend\controllers\UrunController.php(56): Multiple\Backend\Models\urunler->sil(NULL)
#4 [internal function]: Multiple\Backend\Controllers\UrunController->silAction()
#5 [internal function]: Phalcon\Dispatcher->dispatch()
#6 C:\xampp\htdocs\BestShop\public\index.php(98): Phalcon\Mvc\Application->handle()
#7 C:\xampp\htdocs\BestShop\public\index.php(105): Application->main()
#8 {main} thrown in C:\xampp\htdocs\BestShop\apps\backend\models\urunler.php on line 42
```

**Model**
```php
    public function sil($id){
		
		$urun = urunler::findFirst(
				array(
						"conditions" =>"urunNo => $id"
				));
		$urun->delete($id);
		
	}
```
**Controller**
```php
  public function silAction(){
    $urun = new urunler();
    $urun->sil($this->request->getPost('id'));
}
```

**Comment by ashpumpkin** [comment]
try
```PHP
public function sil($id){

    $urun = urunler::findFirst(
            array(
                    "urunNo = :id:",
                    "bind" => ['id' => $id]
            ));
    $urun->delete($id);

}
```
or
```PHP
public function sil($id){
 $urun = urunler::findFirst($id); // urunNo must be PK
    $urun->delete($id);
}
```
or
```PHP
public function sil($id){

    $urun = urunler::findFirst(
            array(
                    "urunNo = $id"
            ));
    $urun->delete($id);

}
```

**Comment by emrullahayin** [comment]
I do not want to delete the record

**Comment by SidRoberts** [comment]
There's an error in the model. The `conditions` property needs to be an SQL-like string and the `bind` property is an associative array of variables. [More information available here](https://docs.phalconphp.com/en/latest/reference/models.html#binding-parameters).

This should work:

```php
public function sil($id){
    $urun = urunler::findFirst(
            array(
                    "conditions" => "urunNo = :urunNo:",
                    "bind"       => ["urunNo" => $id]
            ));
    $urun->delete($id);
}
```

**Comment by rianorie** [comment]
I actually think he was trying to find all records where urunNo is equal to or higher than, which is ">=" and not "=>"

**Comment by equivaQstu** [comment]
I received this error after unintentionally creating a duplicate endpoint in routes.php.  I had two identical POST paths each with a different corresponding function.  I was using a Micro app.  I'm not sure if the error was coming from 	
	$app->setRoutes($routes);
or
	$app->run();
Deleting the duplicate path in my routes.cfg cleared the error.

**Comment by sergeyklay** [comment]
[Phalcon Query Language (PHQL)](https://docs.phalconphp.com/en/latest/reference/phql.html)

<hr>

For questions like this you can use forum: https://forum.phalconphp.com/
