### ISSUE TITLE
syntax error when build using zephir(latest version)

### ISSUE THREAD

**Issue by goqihoo** [phalcon/cphalcon#11509]
```
Zephir\ParseException: Syntax error in /Users/chengang/Downloads/cphalcon/phalcon/paginator/adapter/querybuilder.zep on line 168

	  var groups = totalBuilder->getGroupBy();
	----------------------------^

at Library/CompilerFile.php(525)
#0 Library/Compiler.php(182): Zephir\CompilerFile->preCompile(Object(Zephir\Compiler))
#1 Library/Compiler.php(221): Zephir\Compiler->preCompile('phalcon/paginat...')
#2 Library/Compiler.php(747): Zephir\Compiler->recursivePreCompile('phalcon')
#3 Library/Compiler.php(925): Zephir\Compiler->generate(Object(Zephir\Commands\CommandBuild))
#4 Library/Compiler.php(1031): Zephir\Compiler->compile(Object(Zephir\Commands\CommandBuild), false)
#5 Library/Compiler.php(1101): Zephir\Compiler->install(Object(Zephir\Commands\CommandBuild), false)
#6 Library/Commands/CommandAbstract.php(92): Zephir\Compiler->build(Object(Zephir\Commands\CommandBuild))
#7 Library/Bootstrap.php(200): Zephir\Commands\CommandAbstract->execute(Object(Zephir\Config), Object(Zephir\Logger))
#8 compiler.php(21): Zephir\Bootstrap::boot()
#9 {main}
```

**Comment by goqihoo** [comment]
i got it. it's zephir's problem
fixed in zephir version 0.9
