### ISSUE TITLE
Got segmentation fault on any model running Phalcon 2.1 PHP 7 on CentOS 7

### ISSUE THREAD

**Issue by AC7ION** [phalcon/cphalcon#11661]
Hi,

Today I decided to update my existing app from PHP 5.6 & Phalcon 2.0.10 (here it works) to PHP 7 with Phalcon 2.1.
If I run:

```
[root@auk cli]# php app.php
Segmentation` fault
```

Its executes main task, which looks like:
```
public function mainAction()
{
        $p = Products::findFirst(1);
}
```
Same on any other model.

And using debugger:
```
gdb php
run app.php
bt
```

```
#0  0x00007fffe40ff1c7 in zephir_call_user_function () from /usr/lib64/php/modules/phalcon.so
#1  0x00007fffe41006ce in zephir_call_class_method_aparams () from /usr/lib64/php/modules/phalcon.so
#2  0x00007fffe4101233 in zephir_create_instance_params () from /usr/lib64/php/modules/phalcon.so
#3  0x00007fffe3f97e2b in zim_Phalcon_Di_get () from /usr/lib64/php/modules/phalcon.so
#4  0x00005555557d5fab in dtrace_execute_internal ()
#5  0x00007fffe41005d3 in zephir_call_user_function () from /usr/lib64/php/modules/phalcon.so
#6  0x00007fffe41006ce in zephir_call_class_method_aparams () from /usr/lib64/php/modules/phalcon.so
#7  0x00007fffe3f18a54 in zim_Phalcon_Mvc_Model_Manager_createBuilder () from /usr/lib64/php/modules/phalcon.so
#8  0x00005555557d5fab in dtrace_execute_internal ()
#9  0x00007fffe41005d3 in zephir_call_user_function () from /usr/lib64/php/modules/phalcon.so
#10 0x00007fffe41006ce in zephir_call_class_method_aparams () from /usr/lib64/php/modules/phalcon.so
#11 0x00007fffe4138d7b in zim_Phalcon_Mvc_Model_findFirst () from /usr/lib64/php/modules/phalcon.so
#12 0x00005555557d5fab in dtrace_execute_internal ()
#13 0x0000555555862b44 in ZEND_DO_FCALL_SPEC_HANDLER ()
#14 0x000055555582445b in execute_ex ()
#15 0x00005555557d5e89 in dtrace_execute_ex ()
#16 0x00005555557d789c in zend_call_function ()
#17 0x00007fffe41454de in zephir_call_user_func_array_noex () from /usr/lib64/php/modules/phalcon.so
#18 0x00007fffe40cb9a8 in zim_Phalcon_Cli_Dispatcher_callActionMethod () from /usr/lib64/php/modules/phalcon.so
#19 0x00005555557d5fab in dtrace_execute_internal ()
#20 0x00007fffe41005d3 in zephir_call_user_function () from /usr/lib64/php/modules/phalcon.so
#21 0x00007fffe41006ce in zephir_call_class_method_aparams () from /usr/lib64/php/modules/phalcon.so
#22 0x00007fffe3f9455a in zim_Phalcon_Dispatcher__dispatch () from /usr/lib64/php/modules/phalcon.so
#23 0x00005555557d5fab in dtrace_execute_internal ()
#24 0x00007fffe41005d3 in zephir_call_user_function () from /usr/lib64/php/modules/phalcon.so
#25 0x00007fffe41006ce in zephir_call_class_method_aparams () from /usr/lib64/php/modules/phalcon.so
#26 0x00007fffe40e1ad8 in zim_Phalcon_Dispatcher_dispatch () from /usr/lib64/php/modules/phalcon.so
#27 0x00005555557d5fab in dtrace_execute_internal ()
#28 0x00007fffe41005d3 in zephir_call_user_function () from /usr/lib64/php/modules/phalcon.so
#29 0x00007fffe41006ce in zephir_call_class_method_aparams () from /usr/lib64/php/modules/phalcon.so
#30 0x00007fffe3ffa92a in zim_Phalcon_Cli_Console_handle () from /usr/lib64/php/modules/phalcon.so
#31 0x00005555557d5fab in dtrace_execute_internal ()
#32 0x0000555555862b44 in ZEND_DO_FCALL_SPEC_HANDLER ()
#33 0x000055555582445b in execute_ex ()
#34 0x00005555557d5e89 in dtrace_execute_ex ()
#35 0x000055555586e26f in zend_execute ()
#36 0x00005555557e5b93 in zend_execute_scripts ()
#37 0x0000555555786f48 in php_execute_script ()
#38 0x000055555586fed8 in do_cli ()
#39 0x0000555555624caa in main ()
```

What could I do wrong?
Thanks in advance for any help.

**Comment by sergeyklay** [comment]
#11635 
https://github.com/phalcon/cphalcon/issues/11550
