### ISSUE TITLE
Gettext adapter constructor error with Phalcon 2.1.X

### ISSUE THREAD

**Issue by Gamblt** [phalcon/cphalcon#11760]
The same #11429 issue in 2.1.x branch.

```
[error] 6164#6164: *3 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to private method Phalcon\Translate\Adapter\Gettext::getoptionsdefault() from context 'MyProject\Components\Translate' in /home/gambit/repos/MyProject/app/components/Translate.php:51
Stack trace:
#0 [internal function]: Phalcon\Translate\Adapter\Gettext->prepareOptions(Array)
#1 /home/gambit/repos/MyProject/app/components/Translate.php(51): Phalcon\Translate\Adapter\Gettext->__construct(Array)
#2 /home/gambit/repos/MyProject/app/Bootstrap.php(158): MyProject\Components\Translate->__construct(Object(Phalcon\Config))
#3 /home/gambit/repos/MyProject/public/index.php(15): MyProject\Bootstrap->run()
#4 {main}
```

**Comment by sergeyklay** [comment]
Could you please check the `2.1.x` branch?
