### ISSUE TITLE
Can't select full objects using builder

### ISSUE THREAD

**Issue by Jurigag** [phalcon/cphalcon#11860]
I have some query like this:

```php
$test = $this->modelsManager->createBuilder()
			->columns('Admin.*')
			->from(array('Car' => 'Samochody\Models\Car\Car'))
			->leftJoin('Samochody\Models\Admin\Admin', null, 'Admin')
			->where('Car.id = :car: AND Car.active = :active:', array('car' => $id, 'active' => '1'))
            ->getQuery()
			->execute()
			->getFirst();
		echo($test->getId());
```

All relations etc are fine. `Admin` class is extending `Samochody\Models\User\User` class. But when i try to access columns like this(so i can get admin object) i got:

```
Error message:Column 'first_name' doesn't make part of the column map
File:/var/customers/webs/webtest3/samochody.sidormedia.pl/apps/car/services/CarFrontendService.php
Line:290
Trace:
#0 [internal function]: Phalcon\Mvc\Model::cloneResultMap(Object(Samochody\Models\Admin\Admin), Array, Array, 0, false)
#1 [internal function]: Phalcon\Mvc\Model\Resultset\Simple->current()
#2 /var/customers/webs/webtest3/samochody.sidormedia.pl/apps/car/services/CarFrontendService.php(290): Phalcon\Mvc\Model\Resultset->getFirst()
#3 /var/customers/webs/webtest3/samochody.sidormedia.pl/apps/car/controllers/CarfrontendController.php(61): Samochody\Services\Car\CarFrontendService->getCar('9')
#4 [internal function]: Samochody\Controllers\Car\CarfrontendController->showAction('9')
#5 [internal function]: Phalcon\Dispatcher->dispatch()
#6 /var/customers/webs/webtest3/samochody.sidormedia.pl/public/index.php(118): Phalcon\Mvc\Application->handle()
#7 {main}
```

ColumnMap looks like this in `Admin` class:

```php
public function columnMap()
    {
        //Keys are the real names in the table and
        //the values their names in the application
        $columns = $this->getModelsMetaData()->getAttributes($this);
        $map = [];
        foreach ($columns as $column) { 
			$map[$column] = lcfirst(Text::camelize($column));
		};
        return $map;
    }
```

and it returns:

```
Array
(
    [id] => id
    [first_name] => firstName
    [last_name] => lastName
    [street_address] => streetAddress
    [city_address] => cityAddress
    [postcode_address] => postcodeAddress
    [phone_number] => phoneNumber
    [phone_number2] => phoneNumber2
    [email] => email
    [add_date] => addDate
    [salon] => salon
    [login] => login
    [password] => password
    [session] => session
    [ip_session] => ipSession
    [acl] => acl
    [period_contact] => periodContact
    [register_hash] => registerHash
    [last_login] => lastLogin
    [role] => role
    [active] => active
    [avatar] => avatar
    [change_password] => changePassword
    [managed_salon] => managedSalon
    [forgot_hash] => forgotHash
    [forgot_date] => forgotDate
)
```

Also when i try do ANYTHING with $test, like var_dump it, or toArray() it i have `PHP message: PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted` while changing it to `Car.*` works fine.

Im using php 5.6 and phalcon 2.0.10

Also when i do just `$test = \Samochody\Models\Admin\Admin::findFirst(35);` it works fine and there is no problem at all.

Actually the `_columnMap` for resultset in this case is:

```
'_columnMap' => 
  array (
    'id' => 'id',
    'brand' => 'brand',
    'model' => 'model',
    'body_type' => 'bodyType',
    'version' => 'version',
    'add_date' => 'addDate',
    'admin' => 'admin',
    'registration_number' => 'registrationNumber',
    'vin' => 'vin',
    'driving_gear' => 'drivingGear',
    'gear_box' => 'gearBox',
    'color' => 'color',
    'main_picture' => 'mainPicture',
    'picture_filenames' => 'pictureFilenames',
    'description' => 'description',
    'custom_files' => 'customFiles',
    'sold' => 'sold',
    'true_sold' => 'trueSold',
    'sold_date' => 'soldDate',
    'sold_price' => 'soldPrice',
    'price' => 'price',
    'url_films' => 'urlFilms',
    'salon' => 'salon',
    'offer' => 'offer',
    'year' => 'year',
    'power' => 'power',
    'engine' => 'engine',
    'fuel' => 'fuel',
    'origin' => 'origin',
    'state' => 'state',
    'varnish' => 'varnish',
    'mileage' => 'mileage',
    'combustion' => 'combustion',
    'featured' => 'featured',
    'first_register_date' => 'firstRegisterDate',
    'active' => 'active',
    'buy_price' => 'buyPrice',
  ),
```

**Comment by Jurigag** [comment]
Right now it looks like i need to select from admin, join all cars, group by etc. I think it will be slower than just selecting joined admin from car.

**Comment by Jurigag** [comment]
Well updated to newest version and it works. But still i have problem when for example selecting `Car.*` and `Admin.*` then i have nulls.
