### ISSUE TITLE
phalcon/mvc/model/metadata.zep errors 

### ISSUE THREAD

**Issue by vandr0iy** [phalcon/cphalcon#11993]
I am trying to write an authentication system similar to the one found in vokuro, and I'm having a lot of issues with the sign up step. Precisely, - it's impossible to insert a model in a mySQL DB I am using, whose schema is almost identical to the one found in vokuro, - except for a couple of columns added by me.
Although they're marked as 'NULL' in the mysql table (as in "may have null values or be empty") the model was returning error messages because I wasn't filling them. 
I proceeded to apply one of the solutions found among phalcon's answers in his forums to a similar issue: 
```
add this line to the model's initialize() function:
$this->allowEmptyStringValues(['col1', 'col2', ...]); 
for every column with possible empty string values.
```
After doing this, the application started spitting this kind of errors:

```
Notice: Undefined index: 0 in phalcon/mvc/model/metadata.zep on line 276 in /var/www/localhost/proj/phalcon/app/controllers/SessionController.php on line 48
The meta-data is invalid or is corrupt
#0 [internal function]: Phalcon\Mvc\Model\MetaData->getAttributes(Object(Echelon\Models\Users))
#1 /var/www/localhost/proj/phalcon/app/controllers/SessionController.php(48): Phalcon\Mvc\Model->assign(Array)
#2 [internal function]: Echelon\Controllers\SessionController->signupAction()
#3 [internal function]: Phalcon\Dispatcher->dispatch()
#4 /var/www/localhost/proj/phalcon/public/index.php(29): Phalcon\Mvc\Application->handle()
#5 {main}
```
And, if I remove that line from my model's initialize() function:
```
Notice: Cannot use a scalar value as an array in phalcon/mvc/model/metadata.zep on line 276 in /var/www/localhost/proj/phalcon/app/controllers/SessionController.php on line 48
The meta-data is invalid or is corrupt
#0 [internal function]: Phalcon\Mvc\Model\MetaData->getAttributes(Object(Echelon\Models\Users))
#1 /var/www/localhost/proj/phalcon/app/controllers/SessionController.php(48): Phalcon\Mvc\Model->assign(Array)
#2 [internal function]: Echelon\Controllers\SessionController->signupAction()
#3 [internal function]: Phalcon\Dispatcher->dispatch()
#4 /var/www/localhost/proj/phalcon/public/index.php(29): Phalcon\Mvc\Application->handle()
#5 {main}
```

I suspect some invalid behaviour in my Model's code, but the error messages are pretty obscure, hiding from me the information about what exactly is wrong. 
My goal is simply to allow columns with empty values to be inserted in the DB without provoking too much trouble from the security standpoint.
What could be causing them?
[Here](http://sprunge.us/cZIY) is my model's code, and [Here](http://sprunge.us/ZIFV) is my SessionController's.

PHP version:  5.6.23-pl3-gentoo
OS: Linux **** 4.6.3-gentoo #1 SMP Tue Jun 28 10:20:19 CEST 2016 x86_64
Phalcon: 2.0.13, build date Jun 14 2016 10:33:10 powered by Zephir Version 0.9.2a-dev

**Comment by Jurigag** [comment]
What is your php version and phalcon version and os ?

**Comment by vandr0iy** [comment]
@Jurigag sorry, updating the OP

**Comment by Jurigag** [comment]
And metdata adapter ? Can yo post also mysql code to recreate this users table ?

**Comment by vandr0iy** [comment]
Here is the code to recreate the users table:
```
CREATE TABLE `users` (
  `id` int(10) UNSIGNED NOT NULL,
  `name` varchar(255) NOT NULL,
  `email` varchar(255) NOT NULL,
  `password` char(60) NOT NULL,
  `mustChangePassword` char(1) DEFAULT NULL,
  `profilesId` int(10) UNSIGNED NOT NULL,
  `banned` char(1) NOT NULL,
  `suspended` char(1) NOT NULL,
  `active` char(1) DEFAULT NULL,
  `credits` int(10) UNSIGNED NOT NULL DEFAULT '0',
  `company_name` varchar(255) DEFAULT NULL,
  `address` varchar(255) DEFAULT NULL,
  `city` varchar(255) DEFAULT NULL,
  `province` varchar(255) DEFAULT NULL,
  `cap` char(5) DEFAULT NULL,
  `piva_cf` varchar(255) DEFAULT NULL,
  `phone` varchar(255) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
```

**Comment by Jurigag** [comment]
Still, can't reproduce, such code:

```
$di = new Di\FactoryDefault();
$di->set(
    'db',
    function () {
        $config = [
            'adapter' => 'Mysql',
            'host' => 'localhost',
            'username' => 'root',
            'password' => '',
            'dbname' => 'phalcon_test',
            'port' => 3306,
        ];
        $adapter = '\Phalcon\Db\Adapter\Pdo\\' . $config['adapter'];

        unset($config['adapter']);

        /** @var \Phalcon\Db\AdapterInterface $connection */
        $eventsManager = new \Phalcon\Events\Manager();
        $connection = new $adapter($config);

        return $connection;
    }
);


class Users extends Model
{
    /**
     *
     * @var integer
     */
    public $id;
    /**
     *
     * @var string
     */
    public $name;
    /**
     *
     * @var string
     */
    public $email;
    /**
     *
     * @var string
     */
    public $password;
    /**
     *
     * @var string
     */
    public $mustChangePassword;
    /**
     *
     * @var string
     */
    public $profilesId;
    /**
     *
     * @var string
     */
    public $banned;
    /**
     *
     * @var string
     */
    public $suspended;
    /**
     *
     * @var string
     */
    public $active;

    /**
     *
     * @var integer
     */
    public $credits;

    /**
     *
     * @var string
     */
    public $company_name;

    /**
     *
     * @var string
     */
    public $address;

    /**
     *
     * @var string
     */
    public $city;

    /**
     *
     * @var string
     */
    public $province;

    /**
     *
     * @var string
     */
    public $cap;

    /**
     *
     * @var string
     */
    public $piva_cf;

    /**
     *
     * @var string
     */
    public $phone;

    /**
     * Before create the user assign a password
     */
    public function beforeValidationOnCreate()
    {
        if (empty($this->password)) {
            // Generate a plain temporary password
            $tempPassword = preg_replace('/[^a-zA-Z0-9]/', '', base64_encode(openssl_random_pseudo_bytes(12)));
            // The user must change its password in first login
            $this->mustChangePassword = 'Y';
            // Use this password as default
            $this->password = $this->getDI()
                ->getSecurity()
                ->hash($tempPassword);
        } else {
            // The user must not change its password in first login
            $this->mustChangePassword = 'N';
        }
        // The account must be confirmed via e-mail
        $this->active = 'N';
        // The account is not suspended by default
        $this->suspended = 'N';
        // The account is not banned by default
        $this->banned = 'N';
    }

    public function initialize()
    {

        $this->allowEmptyStringValues(['company_name', 'address', 'city',
                                       'province', 'cap', 'piva_cf', 'phone']);
        $this->belongsTo('profilesId', __NAMESPACE__ . '\Profiles', 'id', array(
            'alias' => 'profile',
            'reusable' => true,
        ));
        $this->hasMany('id', __NAMESPACE__ . '\SuccessLogins', 'usersId', array(
            'alias' => 'successLogins',
            'foreignKey' => array(
                'message' => 'User cannot be deleted because he/she has activity in the system',
            ),
        ));
        $this->hasMany('id', __NAMESPACE__ . '\PasswordChanges', 'usersId', array(
            'alias' => 'passwordChanges',
            'foreignKey' => array(
                'message' => 'User cannot be deleted because he/she has activity in the system',
            ),
        ));
        $this->hasMany('id', __NAMESPACE__ . '\ResetPasswords', 'usersId', array(
            'alias' => 'resetPasswords',
            'foreignKey' => array(
                'message' => 'User cannot be deleted because he/she has activity in the system',
            ),
        ));
    }
}

$user = new Users();

$user->assign(array(
    'name' => 'test',
    'email' => 'test',
    'password' => $di->get('security')->hash('test'),
    'profilesId' => 2,
));

print_r($user->toArray());
```

Returns:

```
Array ( [id] => [name] => test [email] => test [password] => $2y$08$6kQgR8O0Uh9ibC2oMLRBVOHShVaNsdXzpBEGj6E8xR4uH4xR5KHkK [mustChangePassword] => [profilesId] => 2 [banned] => [suspended] => [active] => [credits] => [company_name] => [address] => [city] => [province] => [cap] => [piva_cf] => [phone] => )
```

**Comment by Jurigag** [comment]
Checked it and still working for me. But maybe you just have out-dated metadata ? Try to clear `$config->application->cacheDir . 'meta_data/',`

**Comment by vandr0iy** [comment]
Oh... cleared and retried - everything worked - except the fact that there were a couple of syntax/semantic errors in the config file. 
Anyways, the content of my map-echelon_models_users file was:
```
<?php return array (
  0 => NULL,
  1 => NULL,
); 
```
Thanks a lot, closing this issue.
