### ISSUE TITLE
Phalcon 3.0.0 - Segmentation Fault

### ISSUE THREAD

**Issue by tugrul** [phalcon/cphalcon#12108]
### Test

Don't forget replace underscores to slashes of view file names.
https://gist.github.com/tugrul/a69cd0004b8347bfdc37a17ef4cd1af6
### Coredump

https://we.tl/a5gpcNasw5
### Backtrace

```
(gdb) backtrace
#0  0x00000000006f1839 in gc_zval_possible_root (zv=0x7ffff593b198) at /home/threedot/php-src/Zend/zend_gc.c:143
#1  0x00000000006df908 in zend_hash_destroy (ht=0x7ffff5943858) at /home/threedot/php-src/Zend/zend_hash.c:548
#2  0x00000000006d0fdb in _zval_dtor_func (zvalue=0x7ffff593b198, zvalue@entry=0x7ffff593b4b8) at /home/threedot/php-src/Zend/zend_variables.c:45
#3  0x00000000006c1910 in _zval_dtor (zvalue=0x7ffff593b4b8) at /home/threedot/php-src/Zend/zend_variables.h:35
#4  i_zval_ptr_dtor (zval_ptr=0x7ffff593b4b8) at /home/threedot/php-src/Zend/zend_execute.h:79
#5  _zval_ptr_dtor (zval_ptr=<optimized out>) at /home/threedot/php-src/Zend/zend_execute_API.c:424
#6  0x00000000006f77c7 in zend_object_std_dtor (object=0x7ffff5936a48) at /home/threedot/php-src/Zend/zend_objects.c:54
#7  0x00000000006f77f9 in zend_objects_free_object_storage (object=0x7ffff5936a48) at /home/threedot/php-src/Zend/zend_objects.c:137
#8  0x00000000006fd8dc in zend_objects_store_del_ref_by_handle_ex (handle=143, handlers=<optimized out>) at /home/threedot/php-src/Zend/zend_objects_API.c:226
#9  0x00000000006fd903 in zend_objects_store_del_ref (zobject=0x7ffff7e4ce20) at /home/threedot/php-src/Zend/zend_objects_API.c:178
#10 0x00000000006c1910 in _zval_dtor (zvalue=0x7ffff7e4ce20) at /home/threedot/php-src/Zend/zend_variables.h:35
#11 i_zval_ptr_dtor (zval_ptr=0x7ffff7e4ce20) at /home/threedot/php-src/Zend/zend_execute.h:79
#12 _zval_ptr_dtor (zval_ptr=<optimized out>) at /home/threedot/php-src/Zend/zend_execute_API.c:424
#13 0x00000000006df908 in zend_hash_destroy (ht=0x7ffff7e3ffa0) at /home/threedot/php-src/Zend/zend_hash.c:548
#14 0x00000000006d0fdb in _zval_dtor_func (zvalue=0x7ffff593b198, zvalue@entry=0x7ffff7e1e770) at /home/threedot/php-src/Zend/zend_variables.c:45
#15 0x00000000006c1910 in _zval_dtor (zvalue=0x7ffff7e1e770) at /home/threedot/php-src/Zend/zend_variables.h:35
#16 i_zval_ptr_dtor (zval_ptr=0x7ffff7e1e770) at /home/threedot/php-src/Zend/zend_execute.h:79
#17 _zval_ptr_dtor (zval_ptr=<optimized out>) at /home/threedot/php-src/Zend/zend_execute_API.c:424
#18 0x00000000006f77c7 in zend_object_std_dtor (object=0x7ffff7fdcaf0) at /home/threedot/php-src/Zend/zend_objects.c:54
#19 0x00000000006f77f9 in zend_objects_free_object_storage (object=0x7ffff7fdcaf0) at /home/threedot/php-src/Zend/zend_objects.c:137
#20 0x00000000006fd486 in zend_objects_store_free_object_storage (objects=objects@entry=0xea9260 <executor_globals+928>) at /home/threedot/php-src/Zend/zend_objects_API.c:97
#21 0x00000000006c1f03 in shutdown_executor () at /home/threedot/php-src/Zend/zend_execute_API.c:290
#22 0x00000000006d1fe3 in zend_deactivate () at /home/threedot/php-src/Zend/zend.c:960
#23 0x00000000006713b4 in php_request_shutdown (dummy=<optimized out>) at /home/threedot/php-src/main/main.c:1899
#24 0x000000000077ebe0 in do_cli (argc=-174870120, argv=0x7ffff7e4fd90) at /home/threedot/php-src/sapi/cli/php_cli.c:1177
#25 0x0000000000426207 in main (argc=-174870120, argv=0x7ffff7e4fd90) at /home/threedot/php-src/sapi/cli/php_cli.c:1378
```
### Details
- Phalcon version: 3.0.0
- PHP Version: 5.6.24-0+deb8u1
- Operating System: Debian 8
- Installation type: Compiling from source 
- Zephir version (if any): 0.9.3a-dev-e716dbe641
- Server: Nginx and CLI

**Comment by andresgutierrez** [comment]
Not happening in php7, probably a php5 only issue

**Comment by tugrul** [comment]
@andresgutierrez I have not been tested in php7. So branch 2.1.x have segfault in php5. I'm rolled back to branch 2.0.x.

**Comment by andresgutierrez** [comment]
Confirmed that is segfaulting in php5 (5.5 and 5.6)

**Comment by tugrul** [comment]
I didn't see this error in php 7.0.9

valgrind leak check php 5.6:
```
==3069== Memcheck, a memory error detector
==3069== Copyright (C) 2002-2013, and GNU GPL'd, by Julian Seward et al.
==3069== Using Valgrind-3.10.0 and LibVEX; rerun with -h for copyright info
==3069== Command: /home/tugrul/local/bin/php test.php
==3069== 
==3069== Conditional jump or move depends on uninitialised value(s)
==3069==    at 0x6F98DE: zend_std_get_method (zend_object_handlers.c:1114)
==3069==    by 0x71916A: ZEND_INIT_METHOD_CALL_SPEC_CV_CONST_HANDLER (zend_vm_execute.h:33443)
==3069==    by 0x7058AF: execute_ex (zend_vm_execute.h:363)
==3069==    by 0x6D08BF: zend_execute_scripts (zend.c:1341)
==3069==    by 0x66FA17: php_execute_script (main.c:2613)
==3069==    by 0x77CA7B: do_cli (php_cli.c:994)
==3069==    by 0x426166: main (php_cli.c:1378)
==3069== 
==3069== Conditional jump or move depends on uninitialised value(s)
==3069==    at 0x6F98DE: zend_std_get_method (zend_object_handlers.c:1114)
==3069==    by 0x71916A: ZEND_INIT_METHOD_CALL_SPEC_CV_CONST_HANDLER (zend_vm_execute.h:33443)
==3069==    by 0x7058AF: execute_ex (zend_vm_execute.h:363)
==3069==    by 0x6C046D: zend_call_function (zend_execute_API.c:829)
==3069==    by 0x707756C: zephir_call_user_func_array_noex (phalcon.zep.c:12953)
==3069==    by 0x7240BEF: zephir_call_user_func_array (phalcon.zep.c:4068)
==3069==    by 0x7240BEF: zim_Phalcon_Di_Service_resolve (phalcon.zep.c:60383)
==3069==    by 0x7088272: zephir_call_function_opt (phalcon.zep.c:10511)
==3069==    by 0x7088272: zephir_call_user_function (phalcon.zep.c:12585)
==3069==    by 0x7097C52: zephir_call_class_method_aparams (phalcon.zep.c:12812)
==3069==    by 0x721D07D: zim_Phalcon_Di_get (phalcon.zep.c:20375)
==3069==    by 0x7088272: zephir_call_function_opt (phalcon.zep.c:10511)
==3069==    by 0x7088272: zephir_call_user_function (phalcon.zep.c:12585)
==3069==    by 0x7097C52: zephir_call_class_method_aparams (phalcon.zep.c:12812)
==3069==    by 0x71DC304: zim_Phalcon_Di_getShared (phalcon.zep.c:20459)
==3069== 
==3069== Conditional jump or move depends on uninitialised value(s)
==3069==    at 0x6F98DE: zend_std_get_method (zend_object_handlers.c:1114)
==3069==    by 0x71916A: ZEND_INIT_METHOD_CALL_SPEC_CV_CONST_HANDLER (zend_vm_execute.h:33443)
==3069==    by 0x7058AF: execute_ex (zend_vm_execute.h:363)
==3069==    by 0x7088150: zephir_call_function_opt (phalcon.zep.c:10493)
==3069==    by 0x7088150: zephir_call_user_function (phalcon.zep.c:12585)
==3069==    by 0x7097C52: zephir_call_class_method_aparams (phalcon.zep.c:12812)
==3069==    by 0x733E102: zim_Phalcon_Events_Manager_fireQueue (phalcon.zep.c:61751)
==3069==    by 0x7088272: zephir_call_function_opt (phalcon.zep.c:10511)
==3069==    by 0x7088272: zephir_call_user_function (phalcon.zep.c:12585)
==3069==    by 0x7097C52: zephir_call_class_method_aparams (phalcon.zep.c:12812)
==3069==    by 0x733D2AE: zim_Phalcon_Events_Manager_fire (phalcon.zep.c:61850)
==3069==    by 0x7088272: zephir_call_function_opt (phalcon.zep.c:10511)
==3069==    by 0x7088272: zephir_call_user_function (phalcon.zep.c:12585)
==3069==    by 0x7097C52: zephir_call_class_method_aparams (phalcon.zep.c:12812)
==3069==    by 0x71C1308: zim_Phalcon_Mvc_Dispatcher__handleException (phalcon.zep.c:78630)
==3069== 
==3069== Conditional jump or move depends on uninitialised value(s)
==3069==    at 0x6F98DE: zend_std_get_method (zend_object_handlers.c:1114)
==3069==    by 0x71A788: ZEND_INIT_METHOD_CALL_SPEC_VAR_CONST_HANDLER (zend_vm_execute.h:15764)
==3069==    by 0x7058AF: execute_ex (zend_vm_execute.h:363)
==3069==    by 0x6C046D: zend_call_function (zend_execute_API.c:829)
==3069==    by 0x707756C: zephir_call_user_func_array_noex (phalcon.zep.c:12953)
==3069==    by 0x70D72E9: zephir_call_user_func_array (phalcon.zep.c:4068)
==3069==    by 0x70D72E9: zim_Phalcon_Dispatcher_callActionMethod (phalcon.zep.c:21728)
==3069==    by 0x7088272: zephir_call_function_opt (phalcon.zep.c:10511)
==3069==    by 0x7088272: zephir_call_user_function (phalcon.zep.c:12585)
==3069==    by 0x7097C52: zephir_call_class_method_aparams (phalcon.zep.c:12812)
==3069==    by 0x731C177: zim_Phalcon_Dispatcher__dispatch (phalcon.zep.c:21539)
==3069==    by 0x7088272: zephir_call_function_opt (phalcon.zep.c:10511)
==3069==    by 0x7088272: zephir_call_user_function (phalcon.zep.c:12585)
==3069==    by 0x7097C52: zephir_call_class_method_aparams (phalcon.zep.c:12812)
==3069==    by 0x70B23EE: zim_Phalcon_Dispatcher_dispatch (phalcon.zep.c:21193)
==3069== 
==3069== Conditional jump or move depends on uninitialised value(s)
==3069==    at 0x6F98DE: zend_std_get_method (zend_object_handlers.c:1114)
==3069==    by 0x719BFA: ZEND_INIT_METHOD_CALL_SPEC_UNUSED_CONST_HANDLER (zend_vm_execute.h:25630)
==3069==    by 0x7058AF: execute_ex (zend_vm_execute.h:363)
==3069==    by 0x70782B3: zephir_require_ret (phalcon.zep.c:13081)
==3069==    by 0x736F5C2: zephir_require_zval (phalcon.zep.c:4141)
==3069==    by 0x736F5C2: zim_Phalcon_Mvc_View_Engine_Php_render (phalcon.zep.c:123412)
==3069==    by 0x7088272: zephir_call_function_opt (phalcon.zep.c:10511)
==3069==    by 0x7088272: zephir_call_user_function (phalcon.zep.c:12585)
==3069==    by 0x7097C52: zephir_call_class_method_aparams (phalcon.zep.c:12812)
==3069==    by 0x735C9E7: zim_Phalcon_Mvc_View__engineRender (phalcon.zep.c:87776)
==3069==    by 0x7088272: zephir_call_function_opt (phalcon.zep.c:10511)
==3069==    by 0x7088272: zephir_call_user_function (phalcon.zep.c:12585)
==3069==    by 0x7097C52: zephir_call_class_method_aparams (phalcon.zep.c:12812)
==3069==    by 0x72F258B: zim_Phalcon_Mvc_View_render (phalcon.zep.c:88026)
==3069==    by 0x7088272: zephir_call_function_opt (phalcon.zep.c:10511)
==3069==    by 0x7088272: zephir_call_user_function (phalcon.zep.c:12585)
==3069== 
==3069== Conditional jump or move depends on uninitialised value(s)
==3069==    at 0x6F98DE: zend_std_get_method (zend_object_handlers.c:1114)
==3069==    by 0x71A788: ZEND_INIT_METHOD_CALL_SPEC_VAR_CONST_HANDLER (zend_vm_execute.h:15764)
==3069==    by 0x7058AF: execute_ex (zend_vm_execute.h:363)
==3069==    by 0x6D08BF: zend_execute_scripts (zend.c:1341)
==3069==    by 0x66FA17: php_execute_script (main.c:2613)
==3069==    by 0x77CA7B: do_cli (php_cli.c:994)
==3069==    by 0x426166: main (php_cli.c:1378)
==3069== 
==3069== Invalid read of size 1
==3069==    at 0x6EE8D9: gc_zval_possible_root (zend_gc.c:143)
==3069==    by 0x6DC9A7: zend_hash_destroy (zend_hash.c:548)
==3069==    by 0x6CE07A: _zval_dtor_func (zend_variables.c:45)
==3069==    by 0x6BE9AF: _zval_dtor (zend_variables.h:35)
==3069==    by 0x6BE9AF: i_zval_ptr_dtor (zend_execute.h:79)
==3069==    by 0x6BE9AF: _zval_ptr_dtor (zend_execute_API.c:424)
==3069==    by 0x6F4996: zend_object_std_dtor (zend_objects.c:54)
==3069==    by 0x6F49C8: zend_objects_free_object_storage (zend_objects.c:137)
==3069==    by 0x6FAAAB: zend_objects_store_del_ref_by_handle_ex (zend_objects_API.c:226)
==3069==    by 0x6FAAD2: zend_objects_store_del_ref (zend_objects_API.c:178)
==3069==    by 0x6BE9AF: _zval_dtor (zend_variables.h:35)
==3069==    by 0x6BE9AF: i_zval_ptr_dtor (zend_execute.h:79)
==3069==    by 0x6BE9AF: _zval_ptr_dtor (zend_execute_API.c:424)
==3069==    by 0x6DC9A7: zend_hash_destroy (zend_hash.c:548)
==3069==    by 0x6CE07A: _zval_dtor_func (zend_variables.c:45)
==3069==    by 0x6BE9AF: _zval_dtor (zend_variables.h:35)
==3069==    by 0x6BE9AF: i_zval_ptr_dtor (zend_execute.h:79)
==3069==    by 0x6BE9AF: _zval_ptr_dtor (zend_execute_API.c:424)
==3069==  Address 0x1f169f0c1 is not stack'd, malloc'd or (recently) free'd
==3069== 
==3069== 
==3069== Process terminating with default action of signal 11 (SIGSEGV)
==3069==  Access not within mapped region at address 0x1F169F0C1
==3069==    at 0x6EE8D9: gc_zval_possible_root (zend_gc.c:143)
==3069==    by 0x6DC9A7: zend_hash_destroy (zend_hash.c:548)
==3069==    by 0x6CE07A: _zval_dtor_func (zend_variables.c:45)
==3069==    by 0x6BE9AF: _zval_dtor (zend_variables.h:35)
==3069==    by 0x6BE9AF: i_zval_ptr_dtor (zend_execute.h:79)
==3069==    by 0x6BE9AF: _zval_ptr_dtor (zend_execute_API.c:424)
==3069==    by 0x6F4996: zend_object_std_dtor (zend_objects.c:54)
==3069==    by 0x6F49C8: zend_objects_free_object_storage (zend_objects.c:137)
==3069==    by 0x6FAAAB: zend_objects_store_del_ref_by_handle_ex (zend_objects_API.c:226)
==3069==    by 0x6FAAD2: zend_objects_store_del_ref (zend_objects_API.c:178)
==3069==    by 0x6BE9AF: _zval_dtor (zend_variables.h:35)
==3069==    by 0x6BE9AF: i_zval_ptr_dtor (zend_execute.h:79)
==3069==    by 0x6BE9AF: _zval_ptr_dtor (zend_execute_API.c:424)
==3069==    by 0x6DC9A7: zend_hash_destroy (zend_hash.c:548)
==3069==    by 0x6CE07A: _zval_dtor_func (zend_variables.c:45)
==3069==    by 0x6BE9AF: _zval_dtor (zend_variables.h:35)
==3069==    by 0x6BE9AF: i_zval_ptr_dtor (zend_execute.h:79)
==3069==    by 0x6BE9AF: _zval_ptr_dtor (zend_execute_API.c:424)
==3069==  If you believe this happened as a result of a stack
==3069==  overflow in your program's main thread (unlikely but
==3069==  possible), you can try to increase the size of the
==3069==  main thread stack using the --main-stacksize= flag.
==3069==  The main thread stack size used in this run was 8388608.
==3069== 
==3069== HEAP SUMMARY:
==3069==     in use at exit: 5,899,413 bytes in 29,518 blocks
==3069==   total heap usage: 32,080 allocs, 2,562 frees, 6,166,591 bytes allocated
==3069== 
==3069== LEAK SUMMARY:
==3069==    definitely lost: 0 bytes in 0 blocks
==3069==    indirectly lost: 0 bytes in 0 blocks
==3069==      possibly lost: 0 bytes in 0 blocks
==3069==    still reachable: 5,899,413 bytes in 29,518 blocks
==3069==         suppressed: 0 bytes in 0 blocks
==3069== Reachable blocks (those to which a pointer was found) are not shown.
==3069== To see them, rerun with: --leak-check=full --show-leak-kinds=all
==3069== 
==3069== For counts of detected and suppressed errors, rerun with: -v
==3069== Use --track-origins=yes to see where uninitialised values come from
==3069== ERROR SUMMARY: 18 errors from 7 contexts (suppressed: 0 from 0)
```

**Comment by NOlivNeto** [comment]
Happening in PHP 5.6 here.

**Comment by patrick-zippenfenig** [comment]
Dirty workaround which should not be used in production:
````php
echo $app->handle('/')->getContent();
fastcgi_finish_request();
````
PHP crashes after request is send via fcgi, but at least something happens...

**Comment by patrick-zippenfenig** [comment]
Somehow the shared response object gets corrupted after an exception is thrown. It is created after dispatch. I do not see a relation to the exception handling code. The following code triggers the crash before request shutdown:

````php
$app = new \Phalcon\Mvc\Application($di);
$app->useImplicitView(false); // skip all views, reduce executed code
echo $app->handle('/')->getContent();
$di->remove('response'); // crash! Basically unset($di->_sharedInstances['response'])
````

If the response object is set to non-shared, it is working fine, but breaks other functionality. As long as the response object is created anytime before [application.zep#L372](https://github.com/phalcon/cphalcon/blob/master/phalcon/mvc/application.zep#L372) it is does not trigger the error. Acceptable workaround, but not a solution.
````php
$app = new \Phalcon\Mvc\Application($di);
$response = $di->get('response');
echo $app->handle('/')->getContent(); // no crash afterwards
````

Calling ````$app->handle()```` in a catch block does not trigger the error. (Just to rule that out)
````php
try{
    throw new \Exception('foo');
} catch (\Exception $e) {
    $app = new \Phalcon\Mvc\Application($di);
    echo $app->handle('/not/throwing/an/exception')->getContent();
    $di->remove('response'); // working fine
}
````
