### ISSUE TITLE
Fatal error: Uncaught Error: Access to undeclared static property: Phalcon\Di::$_default

### ISSUE THREAD

**Issue by 3078825** [phalcon/cphalcon#12110]
```php
( ! ) Fatal error: Uncaught Error: Access to undeclared static property: Phalcon\Di::$_default in D:\website\test\applications\common\config\service.php:22 
Stack trace: 
#0 [internal function]: Phalcon\Di->__construct() 
#1 D:\website\test\applications\common\config\service.php(22): Phalcon\Di\FactoryDefault->__construct() 
#2 D:\website\test\backend\index.php(21): include('D:\\website\\test\\...') 
#3 {main} Next Error: Access to undeclared static property: Phalcon\Di::$_default in D:\website\test\applications\common\config\service.php on line 22

```
> Provide minimal script to reproduce the issue

```php
<?php
use Phalcon\Di;
use Phalcon\Di\FactoryDefault;
use Phalcon\Tag;
use Phalcon\Mvc\Url;
use Phalcon\escaper;
use Phalcon\Http\Response;
use Phalcon\Http\Request;
use Phalcon\Mvc\Application;
use Phalcon\Mvc\View;
use Phalcon\Mvc\View\Engine\Volt;
use Phalcon\Db\Adapter\Pdo\Mysql as DB;
use Phalcon\Events\Manager as EventsManager;
use Phalcon\Mvc\Dispatcher as MvcDispatcher;
use Phalcon\Db\Profiler as DbProfiler;
use Phalcon\Logger;
use Phalcon\Logger\Formatter\Line as LineFormatter;
use Phalcon\Logger\Adapter\File as FileAdapter;
use Phalcon\Mvc\Model\Transaction\Manager as TransactionManager;
use Phalcon\Text;

$di = new \Phalcon\DI\FactoryDefault();
```
### Details

* Phalcon version:3.0.0
* PHP Version:7.0.7
* Operating System:Windows 10 / Apache 2.4 x64 (php7_module) / PHP 7.07 x64 
* Installation type:phalcon_x64_vc14_php7.0.0_3.0.0_nts.zip
* Server: Apache

**Comment by Dublerq** [comment]
What's the point of `use Phalcon\Di\FactoryDefault;` if you use `$di = new \Phalcon\DI\FactoryDefault();` ?

Nevertheless DI\FactoryDefault is designed to be created only once. I suspect that you might have created another FactoryDefault instance before, and you're trying to make another one.

**Comment by sergeyklay** [comment]
https://github.com/phalcon/cphalcon/issues/12056

**Comment by pedro151** [comment]
same error occurs in:
    Phalcon version:3.0.0
    PHP Version:7.0.10
    Operating System:Windows 10 / Apache 2.4 x86 (php7_module) / PHP 7.0.10 x86
