### ISSUE TITLE
SetLocale() not support multiple parameters

### ISSUE THREAD

**Issue by xerron** [phalcon/cphalcon#12202]
https://docs.phalconphp.com/en/latest/api/Phalcon_Translate_Adapter_Gettext.html

``` php
$gettext->setLocale(LC_ALL, 'de_DE@euro', 'de_DE', 'de', 'ge');
```

error:

``` text
Wrong number of parameters
#0 /home/xerron/Repo/php/u-w-u.com/modules/system/system.routing.php(130): Phalcon\Translate\Adapter\Gettext->setLocale(6, 'es_PE', 'es_ES', 'es')
#1 [internal function]: {closure}()
#2 /home/xerron/Repo/php/u-w-u.com/web/index.php(68): Phalcon\Mvc\Micro->handle()
#3 {main}
```

**Comment by xerron** [comment]
https://github.com/phalcon/cphalcon/blob/master/phalcon/translate/adapter/gettext.zep#L193

second parameters is a String

**Comment by sergeyklay** [comment]
Refs: https://github.com/phalcon/zephir/issues/938

**Comment by niden** [comment]
Closing in favor of #13855. Will revisit if the community votes for it, or in later versions.

**Comment by niden** [comment]
This has been fixed with a0817c78ed

Also updating the docblock to be more specific
