### ISSUE TITLE
Namespace model aliases doesn't work on where condition

### ISSUE THREAD

**Issue by Jurigag** [phalcon/cphalcon#12269]
### Expected and Actual Behavior

Sometimes im using in my app `::query` instead of query builder. Since you can't use alias for model from which you are doing query(like set alias for from) then i want to use namespace model alias in where so i don't need to write full namespace of model. But this is not working. Phalcon is just not replacting this model namespace alias.

``` php
Unknown model or alias 'S:StudentLocation' (11), when preparing: SELECT COUNT(DISTINCT studentId) FROM [Suzuki\Module\Student\Model\StudentLocation] LEFT JOIN [T:Location] AS [Location] ON locationId = Location.id WHERE teacherId = :teacherId: AND instrumentId = :instrumentId: AND [S:StudentLocation].active = 1
#0 [internal function]: Phalcon\Mvc\Model\Query->_getQualified(Array) #1 [internal function]: Phalcon\Mvc\Model\Query->_getExpression(Array, true) #2 [internal function]: Phalcon\Mvc\Model\Query->_getExpression(Array, true) #3 [internal function]: Phalcon\Mvc\Model\Query->_getExpression(Array, true) #4 [internal function]: Phalcon\Mvc\Model\Query->_getExpression(Array) #5 [internal function]: Phalcon\Mvc\Model\Query->_prepareSelect() #6 [internal function]: Phalcon\Mvc\Model\Query->parse() #7 [internal function]: Phalcon\Mvc\Model\Query->execute() #8 [internal function]: Phalcon\Mvc\Model::find(Array) #9 /var/www/suzuki/Module/Teacher/Model/TeacherInstrument.php(110): Phalcon\Mvc\Model\Criteria->execute() #10 [internal function]: Suzuki\Module\Teacher\Model\TeacherInstrument->beforeDelete() #11 [internal function]: Phalcon\Mvc\Model->fireEventCancel('beforeDelete') #12 /var/www/suzuki/Module/Teacher/Service/InstrumentService.php(242): Phalcon\Mvc\Model->delete() #13 /var/www/suzuki/Module/Teacher/Controller/InstrumentController.php(104): Suzuki\Module\Teacher\Service\InstrumentService->deleteTeacher('2') #14 [internal function]: Suzuki\Module\Teacher\Controller\InstrumentController->deleteAction('2') #15 [internal function]: Phalcon\Dispatcher->callActionMethod(Object(Suzuki\Module\Teacher\Controller\InstrumentController), 'deleteAction', Array) #16 [internal function]: Phalcon\Dispatcher->_dispatch() #17 [internal function]: Phalcon\Dispatcher->dispatch() #18 /var/www/suzuki/public/index.php(28): Phalcon\Mvc\Application->handle() #19 {main}
```

``` php
$studentsCount = query()
            ->columns('COUNT(DISTINCT studentId)')
            ->leftJoin('T:Location', 'locationId = Location.id', 'Location')
            ->where('teacherId = :teacherId: AND instrumentId = :instrumentId: AND S:StudentLocation.active = 1', [
                'teacherId' => $this->teacherId,
                'instrumentId' => $this->instrumentId
            ])
            ->execute()
            ->getFirst()->offsetGet("0");
```
### Details
- Phalcon version: 3.0.2
- PHP Version: 7.0.10
- Operating System: debian 8
- Installation type: Compiling from source
- Zephir version (if any):
- Server: Nginx

**Comment by sergeyklay** [comment]
@Jurigag Could you please privide model definition?

**Comment by Jurigag** [comment]
StudentLocation - http://pastebin.com/wJhVBzcc
Location - http://pastebin.com/6UxHZrRq

**Comment by ahmadmayahi** [comment]
I have the same issue.

**Comment by Deathamns** [comment]
As namespace aliases have been [removed in Phalcon 4](https://github.com/phalcon/cphalcon/issues/14437), is this issue still relevant?

**Comment by niden** [comment]
@Deathamns Thanks for catching this. 

Ref: https://github.com/phalcon/cphalcon/pull/14028
