### ISSUE TITLE
couldn't run on php 7.1.0: Program terminated with signal 11, Segmentation fault.

### ISSUE THREAD

**Issue by noname007** [phalcon/cphalcon#12477]
> Questions should go to https://forum.phalconphp.com
> Documentation issues should go to https://github.com/phalcon/docs/issues

### Expected and Actual Behavior

run ./sbin/php-fpm at php root dir and output

> **Segmentation fault.**

> Provide output if related. Provide coredump if any. Use https://github.com/phalcon/cphalcon/wiki/Generating-a-backtrace as reference

```shell
....
Reading symbols from /lib64/libselinux.so.1...(no debugging symbols found)...done.
Loaded symbols for /lib64/libselinux.so.1
Reading symbols from /home/software/php7.1.0rc/lib/php/extensions/no-debug-non-zts-20160303/phalcon.so...(no debugging symbols found)...done.
Loaded symbols for /home/software/php7.1.0rc/lib/php/extensions/no-debug-non-zts-20160303/phalcon.so
Core was generated by `./sbin/php-fpm'.
Program terminated with signal 11, Segmentation fault.
#0  0x000000000085577b in zval_addref_p (ce=0x1dcb980, iface=0x1cbc0e0) at /home/software/php-7.1.0/Zend/zend_types.h:829
829		return ++GC_REFCOUNT(Z_COUNTED_P(pz));
Missing separate debuginfos, use: debuginfo-install bzip2-libs-1.0.5-7.el6_0.x86_64 cyrus-sasl-lib-2.1.23-13.el6_3.1.x86_64 glibc-2.12-1.149.el6_6.5.x86_64 keyutils-libs-1.4-4.el6.x86_64 krb5-libs-1.10.3-10.el6_4.6.x86_64 libcom_err-1.41.12-18.el6.x86_64 libcurl-7.19.7-52.el6.x86_64 libgcc-4.4.7-16.el6.x86_64 libicu-4.2.1-14.el6.x86_64 libidn-1.18-2.el6.x86_64 libmcrypt-2.5.8-9.el6.x86_64 libselinux-2.0.94-5.3.el6_4.1.x86_64 libssh2-1.4.2-1.el6.x86_64 libstdc++-4.4.7-16.el6.x86_64 libtool-ltdl-2.2.6-15.5.el6.x86_64 libxml2-2.7.6-21.el6_8.1.x86_64 nspr-4.9.2-1.el6.x86_64 nss-3.14.0.0-12.el6.x86_64 nss-softokn-freebl-3.12.9-11.el6.x86_64 nss-util-3.14.0.0-2.el6.x86_64 openldap-2.4.23-31.el6.x86_64 openssl-1.0.1e-48.el6_8.3.x86_64 zlib-1.2.3-29.el6.x86_64
(gdb) bt
#0  0x000000000085577b in zval_addref_p (ce=0x1dcb980, iface=0x1cbc0e0) at /home/software/php-7.1.0/Zend/zend_types.h:829
#1  do_inherit_iface_constant (ce=0x1dcb980, iface=0x1cbc0e0) at /home/software/php-7.1.0/Zend/zend_inheritance.c:1005
#2  zend_do_implement_interface (ce=0x1dcb980, iface=0x1cbc0e0) at /home/software/php-7.1.0/Zend/zend_inheritance.c:1054
#3  0x000000000081b5e0 in zend_class_implements (class_entry=0x1dcb980, num_interfaces=<value optimized out>) at /home/software/php-7.1.0/Zend/zend_API.c:2690
#4  0x00007fcb1e1eda9f in zephir_Phalcon_Mvc_Model_Query_Builder_init () from /home/software/php7.1.0rc/lib/php/extensions/no-debug-non-zts-20160303/phalcon.so
#5  0x00007fcb1e21761f in zm_startup_phalcon () from /home/software/php7.1.0rc/lib/php/extensions/no-debug-non-zts-20160303/phalcon.so
#6  0x000000000081a413 in zend_startup_module_ex (module=0x1af1c30) at /home/software/php-7.1.0/Zend/zend_API.c:1843
#7  0x000000000081a4ac in zend_startup_module_zval (zv=<value optimized out>) at /home/software/php-7.1.0/Zend/zend_API.c:1858
#8  0x00000000008222d3 in zend_hash_apply (ht=0x1196140, apply_func=0x81a4a0 <zend_startup_module_zval>) at /home/software/php-7.1.0/Zend/zend_hash.c:1508
#9  0x000000000081d01a in zend_startup_modules () at /home/software/php-7.1.0/Zend/zend_API.c:1969
#10 0x00000000007b6c15 in php_module_startup (sf=<value optimized out>, additional_modules=<value optimized out>, num_additional_modules=<value optimized out>)
    at /home/software/php-7.1.0/main/main.c:2256
#11 0x00000000008c6e75 in php_cgi_startup (sapi_module=<value optimized out>) at /home/software/php-7.1.0/sapi/fpm/fpm/fpm_main.c:838
#12 0x00000000008c76fb in main (argc=1, argv=0x7fff91e2a1e8) at /home/software/php-7.1.0/sapi/fpm/fpm/fpm_main.c:1811
```
> Provide minimal script to reproduce the issue

```php
// paste code
```
### Details

* Phalcon version: (`3.0.2`)
* PHP Version:
```shell
PHP 7.1.0 (cli) (built: Dec 15 2016 16:17:30) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.1.0-dev, Copyright (c) 1998-2016 Zend Technologies
Segmentation fault (core dumped)
```
* Operating System: centos 6.5 final
* Installation type: Compiling from source
* Zephir version (if any):

**Comment by sergeyklay** [comment]
https://github.com/phalcon/cphalcon/issues/12055
