### ISSUE TITLE
Segmentation fault when try use reserved keyword in model::find()

### ISSUE THREAD

**Issue by createanduse** [phalcon/cphalcon#12711]
### Expected and Actual Behavior
Code:
```php
$model = Menu::find([
  'conditions' => 'menu_location_id = ?1',
  'bind' => [
    1 => $locationId,
  ],
  'order' => 'order ASC, title ASC',
]);
print gettype($model);
```
Expected:
```php
object
```
Actual:
```
Segmentation fault
```

I'm trying to use order on field with reserved keyword. I know workaround with brackets on reserved keyword, but i think it shouldn't work like this (segmentation fault).

Result:
segmentation fault  php -S 127.0.0.1:9900 -t public (error code: 139)

* Phalcon version: (`php --ri phalcon`)

Web framework delivered as a C-extension for PHP
phalcon => enabled
Author => Phalcon Team and contributors
Version => 3.0.4
Build Date => Feb 28 2017 08:26:30
Powered by Zephir => Version 0.9.6a-dev-aef205594b
Directive => Local Value => Master Value
phalcon.db.escape_identifiers => On => On
phalcon.db.force_casting => Off => Off
phalcon.orm.events => On => On
phalcon.orm.virtual_foreign_keys => On => On
phalcon.orm.column_renaming => On => On
phalcon.orm.not_null_validations => On => On
phalcon.orm.exception_on_failed_save => Off => Off
phalcon.orm.enable_literals => On => On
phalcon.orm.late_state_binding => Off => Off
phalcon.orm.enable_implicit_joins => On => On
phalcon.orm.cast_on_hydrate => Off => Off
phalcon.orm.ignore_unknown_columns => Off => Off

* PHP Version: (`php -v`)

PHP 5.6.30 (cli) (built: Mar 15 2017 09:25:39)
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Xdebug v2.5.1, Copyright (c) 2002-2017, by Derick Rethans

* Operating System:

uname -a:
Darwin deathstar.local 15.6.0 Darwin Kernel Version 15.6.0: Thu Sep  1 15:01:16 PDT 2016; root:xnu-3248.60.11~2/RELEASE_X86_64 x86_64

* Installation type:

Installed form brew

* Zephir version (if any):

0.9.6a-dev-aef205594b

* Server:

PHP built in development server

* Other related info (Database, table schema): 

CREATE TABLE `menu` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `menu_location_id` int(11) unsigned NOT NULL,
  `url` text CHARACTER SET utf8 NOT NULL,
  `title` varchar(128) COLLATE utf8_general_ci NOT NULL,
  `order` int(11) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

**Comment by Jurigag** [comment]
```
#0  zval_delref_p (pz=<optimized out>) at /root/.phpbrew/build/php-5.6.28/Zend/zend.h:411
411             return --pz->refcount__gc;
(gdb) bt
#0  zval_delref_p (pz=<optimized out>) at /root/.phpbrew/build/php-5.6.28/Zend/zend.h:411
#1  i_zval_ptr_dtor (zval_ptr=0x0) at /root/.phpbrew/build/php-5.6.28/Zend/zend_execute.h:76
#2  _zval_ptr_dtor (zval_ptr=0x7f3bf5859510) at /root/.phpbrew/build/php-5.6.28/Zend/zend_execute_API.c:424
#3  0x00007f3bee60478c in pp_pop_parser_stack () from /root/.phpbrew/php/php-5.6.28/lib/php/extensions/no-debug-non-zts-20131226/phalcon.so
#4  0x00007f3bee60512b in phql_ () from /root/.phpbrew/php/php-5.6.28/lib/php/extensions/no-debug-non-zts-20131226/phalcon.so
#5  0x00007f3bee607ec2 in phql_internal_parse_phql () from /root/.phpbrew/php/php-5.6.28/lib/php/extensions/no-debug-non-zts-20131226/phalcon.so
#6  0x00007f3bee60837d in phql_parse_phql () from /root/.phpbrew/php/php-5.6.28/lib/php/extensions/no-debug-non-zts-20131226/phalcon.so
#7  0x00007f3bee5193bf in zim_Phalcon_Mvc_Model_Query_parse () from /root/.phpbrew/php/php-5.6.28/lib/php/extensions/no-debug-non-zts-20131226/phalcon.so
#8  0x00007f3bee8d3dd5 in xdebug_execute_internal (current_execute_data=0x7ffc300d5530, fci=0x7ffc300d56c0, return_value_used=1)
    at /root/.phpbrew/build/php-5.6.28/ext/xdebug/xdebug.c:2074
#9  0x00007f3bee2fda34 in zephir_call_function_opt () from /root/.phpbrew/php/php-5.6.28/lib/php/extensions/no-debug-non-zts-20131226/phalcon.so
#10 0x00007f3bee2f9863 in zephir_call_user_function () from /root/.phpbrew/php/php-5.6.28/lib/php/extensions/no-debug-non-zts-20131226/phalcon.so
#11 0x00007f3bee2fa46f in zephir_call_class_method_aparams () from /root/.phpbrew/php/php-5.6.28/lib/php/extensions/no-debug-non-zts-20131226/phalcon.so
#12 0x00007f3bee51b839 in zim_Phalcon_Mvc_Model_Query_execute () from /root/.phpbrew/php/php-5.6.28/lib/php/extensions/no-debug-non-zts-20131226/phalcon.so
#13 0x00007f3bee8d3dd5 in xdebug_execute_internal (current_execute_data=0x7ffc300d5bb0, fci=0x7ffc300d5d40, return_value_used=1)
    at /root/.phpbrew/build/php-5.6.28/ext/xdebug/xdebug.c:2074
#14 0x00007f3bee2fda34 in zephir_call_function_opt () from /root/.phpbrew/php/php-5.6.28/lib/php/extensions/no-debug-non-zts-20131226/phalcon.so
#15 0x00007f3bee2f9863 in zephir_call_user_function () from /root/.phpbrew/php/php-5.6.28/lib/php/extensions/no-debug-non-zts-20131226/phalcon.so
#16 0x00007f3bee2fa46f in zephir_call_class_method_aparams () from /root/.phpbrew/php/php-5.6.28/lib/php/extensions/no-debug-non-zts-20131226/phalcon.so
#17 0x00007f3bee4c14c8 in zim_Phalcon_Mvc_Model_find () from /root/.phpbrew/php/php-5.6.28/lib/php/extensions/no-debug-non-zts-20131226/phalcon.so
#18 0x00007f3bee8d3dd5 in xdebug_execute_internal (current_execute_data=0x7f3bf59e7268, fci=0x0, return_value_used=1)
    at /root/.phpbrew/build/php-5.6.28/ext/xdebug/xdebug.c:2074
#19 0x000000000085e1a0 in zend_do_fcall_common_helper_SPEC (execute_data=<optimized out>) at /root/.phpbrew/build/php-5.6.28/Zend/zend_vm_execute.h:560
#20 0x00000000007f3678 in execute_ex (execute_data=0x7f3bf59e7268) at /root/.phpbrew/build/php-5.6.28/Zend/zend_vm_execute.h:363
#21 0x00007f3bee8d32c8 in xdebug_execute_ex (execute_data=0x7f3bf59e7268) at /root/.phpbrew/build/php-5.6.28/ext/xdebug/xdebug.c:1916
#22 0x00000000007ba4b0 in zend_execute_scripts (type=type@entry=8, retval=retval@entry=0x0, file_count=file_count@entry=3) at /root/.phpbrew/build/php-5.6.28/Zend/zend.c:1341
#23 0x0000000000758342 in php_execute_script (primary_file=primary_file@entry=0x7ffc300d8720) at /root/.phpbrew/build/php-5.6.28/main/main.c:2613
#24 0x0000000000860198 in do_cli (argc=2, argv=0x23b9d90) at /root/.phpbrew/build/php-5.6.28/sapi/cli/php_cli.c:998
#25 0x0000000000436110 in main (argc=2, argv=0x23b9d90) at /root/.phpbrew/build/php-5.6.28/sapi/cli/php_cli.c:1382
```
