### ISSUE TITLE
CodeCeption MysqlTest fails with segmentation fault

### ISSUE THREAD

**Issue by sjinks** [phalcon/cphalcon#12815]
> Questions should go to https://forum.phalconphp.com
> Documentation issues should go to https://github.com/phalcon/docs/issues

### Expected and Actual Behavior

> **Describe what you are trying to achieve and what goes wrong.**
```
E MysqlTest: List tables

Program received signal SIGSEGV, Segmentation fault.
```

> Provide output if related. Provide coredump if any. Use https://github.com/phalcon/cphalcon/wiki/Generating-a-backtrace as reference
```
Program received signal SIGSEGV, Segmentation fault.
0x0000555555ce887b in php_strlcpy (dst=0x69 <error: Cannot access memory at address 0x69>, src=0x5555563c0f06 "00000", siz=6) at /tmp/php-build/source/7.0.18/main/strlcpy.c:78
78                              if ((*d++ = *s++) == 0)
(gdb) bt
#0  0x0000555555ce887b in php_strlcpy (dst=0x69 <error: Cannot access memory at address 0x69>, src=0x5555563c0f06 "00000", siz=6) at /tmp/php-build/source/7.0.18/main/strlcpy.c:78
#1  0x00005555559d8e78 in zim_PDO_query (execute_data=0x7ffff7efff40, return_value=0x7fffffff96b0) at /tmp/php-build/source/7.0.18/ext/pdo/pdo_dbh.c:1070
#2  0x0000555555d7c808 in zend_call_function (fci=0x7fffffff93b0, fci_cache=0x7fffffff9380) at /tmp/php-build/source/7.0.18/Zend/zend_execute_API.c:878
#3  0x00007fffe525b419 in zephir_call_user_function (object_pp=0x7fffffff96a0, obj_ce=0x555556949910, type=zephir_fcall_method, function_name=0x7fffffff94c0, retval_ptr=0x7fffffff96b0, cache_entry=0x0, cache_slot=0, param_count=1, params=0x7fffffff9730)
    at /opt/cphalcon/ext/kernel/fcall.c:288
#4  0x00007fffe525bc86 in zephir_call_class_method_aparams (return_value_ptr=0x7fffffff96b0, ce=0x555556949910, type=zephir_fcall_method, object=0x7fffffff96a0, method_name=0x7fffe57f692f "query", method_len=5, cache_entry=0x0, cache_slot=0, param_count=1,
    params=0x7fffffff9730) at /opt/cphalcon/ext/kernel/fcall.c:481
#5  0x00007fffe52b4292 in zim_Phalcon_Db_Adapter_Pdo_query (execute_data=0x7ffff7effeb0, return_value=0x7fffffff9ca0) at /opt/cphalcon/ext/phalcon/db/adapter/pdo.zep.c:566
#6  0x0000555555d7c808 in zend_call_function (fci=0x7fffffff9a30, fci_cache=0x7fffffff9a00) at /tmp/php-build/source/7.0.18/Zend/zend_execute_API.c:878
#7  0x00007fffe525b419 in zephir_call_user_function (object_pp=0x7ffff7effe50, obj_ce=0x555556a7bbc0, type=zephir_fcall_method, function_name=0x7fffffff9b40, retval_ptr=0x7fffffff9ca0, cache_entry=0x0, cache_slot=0, param_count=3, params=0x7fffffff9ce0)
    at /opt/cphalcon/ext/kernel/fcall.c:288
#8  0x00007fffe525bc86 in zephir_call_class_method_aparams (return_value_ptr=0x7fffffff9ca0, ce=0x555556a7bbc0, type=zephir_fcall_method, object=0x7ffff7effe50, method_name=0x7fffe57bca6f "query", method_len=5, cache_entry=0x0, cache_slot=0, param_count=3,
    params=0x7fffffff9ce0) at /opt/cphalcon/ext/kernel/fcall.c:481
#9  0x00007fffe528cf2b in zim_Phalcon_Db_Adapter_fetchAll (execute_data=0x7ffff7effe30, return_value=0x7fffffffa230) at /opt/cphalcon/ext/phalcon/db/adapter.zep.c:408
#10 0x0000555555d7c808 in zend_call_function (fci=0x7fffffff9fc0, fci_cache=0x7fffffff9f90) at /tmp/php-build/source/7.0.18/Zend/zend_execute_API.c:878
#11 0x00007fffe525b419 in zephir_call_user_function (object_pp=0x7ffff7effdf0, obj_ce=0x555556a7bbc0, type=zephir_fcall_method, function_name=0x7fffffffa0d0, retval_ptr=0x7fffffffa230, cache_entry=0x0, cache_slot=0, param_count=2, params=0x7fffffffa2a0)
    at /opt/cphalcon/ext/kernel/fcall.c:288
#12 0x00007fffe525bc86 in zephir_call_class_method_aparams (return_value_ptr=0x7fffffffa230, ce=0x555556a7bbc0, type=zephir_fcall_method, object=0x7ffff7effdf0, method_name=0x7fffe57c1db9 "fetchall", method_len=8, cache_entry=0x0, cache_slot=0, param_count=2,
    params=0x7fffffffa2a0) at /opt/cphalcon/ext/kernel/fcall.c:481
#13 0x00007fffe529b98f in zim_Phalcon_Db_Adapter_listTables (execute_data=0x7ffff7effdd0, return_value=0x7ffff7effcc0) at /opt/cphalcon/ext/phalcon/db/adapter.zep.c:2178
#14 0x0000555555e03b20 in ZEND_DO_FCALL_SPEC_HANDLER () at /tmp/php-build/source/7.0.18/Zend/zend_vm_execute.h:842
#15 0x0000555555e02427 in execute_ex (ex=0x7ffff7effc30) at /tmp/php-build/source/7.0.18/Zend/zend_vm_execute.h:414
#16 0x0000555555d7c62d in zend_call_function (fci=0x7fffffffa550, fci_cache=0x7fffffffa520) at /tmp/php-build/source/7.0.18/Zend/zend_execute_API.c:858
#17 0x0000555555b37b39 in zif_call_user_func_array (execute_data=0x7ffff7effbb0, return_value=0x7ffff7eff7b0) at /tmp/php-build/source/7.0.18/ext/standard/basic_functions.c:4808
#18 0x0000555555e033b5 in ZEND_DO_FCALL_BY_NAME_SPEC_HANDLER () at /tmp/php-build/source/7.0.18/Zend/zend_vm_execute.h:714
#19 0x0000555555e02427 in execute_ex (ex=0x7ffff7eff1a0) at /tmp/php-build/source/7.0.18/Zend/zend_vm_execute.h:414
#20 0x0000555555d7c62d in zend_call_function (fci=0x7fffffffa860, fci_cache=0x7fffffffa830) at /tmp/php-build/source/7.0.18/Zend/zend_execute_API.c:858
#21 0x0000555555a535be in zim_reflection_method_invokeArgs (execute_data=0x7ffff7eff120, return_value=0x7ffff7efedb0) at /tmp/php-build/source/7.0.18/ext/reflection/php_reflection.c:3355
#22 0x0000555555e03b20 in ZEND_DO_FCALL_SPEC_HANDLER () at /tmp/php-build/source/7.0.18/Zend/zend_vm_execute.h:842
#23 0x0000555555e02427 in execute_ex (ex=0x7ffff7efa040) at /tmp/php-build/source/7.0.18/Zend/zend_vm_execute.h:414
#24 0x0000555555e02628 in zend_execute (op_array=0x555556cc6020, return_value=0x0) at /tmp/php-build/source/7.0.18/Zend/zend_vm_execute.h:458
#25 0x0000555555d99407 in zend_execute_scripts (type=8, retval=0x0, file_count=3) at /tmp/php-build/source/7.0.18/Zend/zend.c:1443
#26 0x0000555555cd3906 in php_execute_script (primary_file=0x7fffffffcfd0) at /tmp/php-build/source/7.0.18/main/main.c:2492
#27 0x0000555555e72273 in do_cli (argc=5, argv=0x5555567fe730) at /tmp/php-build/source/7.0.18/sapi/cli/php_cli.c:977
#28 0x0000555555e73716 in main (argc=5, argv=0x5555567fe730) at /tmp/php-build/source/7.0.18/sapi/cli/php_cli.c:1347
```

### Details

* Phalcon version: (`php --ri phalcon`) 3.1.2
* PHP Version: (`php -v`) PHP 7.0.18 ZTS DEBUG
* Operating System: Ubuntu 16.10 x64
* Installation type: Compiling from source
* Zephir version (if any): Version 0.9.7-dbc0b339b4
* Server: cli

**Comment by sjinks** [comment]
```
#0  0x0000555555ce887b in php_strlcpy (dst=0x69 <error: Cannot access memory at address 0x69>, src=0x5555563c0f06 "00000", siz=6) at /tmp/php-build/source/7.0.18/main/strlcpy.c:78
        d = 0x6a <error: Cannot access memory at address 0x6a>
        s = 0x5555563c0f07 "0000"
        n = 5
#1  0x00005555559d8e78 in zim_PDO_query (execute_data=0x7ffff7efff40, return_value=0x7fffffff96b0) at /tmp/php-build/source/7.0.18/ext/pdo/pdo_dbh.c:1070
        stmt = 0x55555907e3a0
        statement = 0x5555590f81a8 "SHOW TABLES"
        statement_len = 11
        dbh_obj = 0x55555907e398
        dbh = 0x31
```

**Comment by sjinks** [comment]
At that

```php
<?php
$config = [
    "host"     => "127.0.0.1",
    "dbname"   => "phalcon_test",
    "port"     => 3306,
    "username" => "root",
    "password" => "",
];

$db = new Phalcon\Db\Adapter\Pdo\Mysql($config);
print_r($db->listTables("phalcon_test"));
print_r($db->listTables());
```

works as expected.

**Comment by sergeyklay** [comment]
Cc: @DavertMik
