### ISSUE TITLE
FindFirst irregular return

### ISSUE THREAD

**Issue by gamalan** [phalcon/cphalcon#12830]
> Questions should go to https://forum.phalconphp.com
> Documentation issues should go to https://github.com/phalcon/docs/issues

Continuing my question in forum. [https://forum.phalconphp.com/discussion/16031/ask-findfirst-sometimes-return-stdclass](url)

### Expected and Actual Behavior
Expected, Model::FindFirst() normally should return Model if found and false if not.
Actual, happen irregularly, and in only 2 model. All model is using same base class. Sometimes it return stdClass which is not Model or ResultSet, and don't contain method update().

Because it happen irregularly(around 63 case, since 22 April) and only in some model, i'm not sure how to approach this.

NB : the record does exist.

> Provide output if related. Provide coredump if any. Use https://github.com/phalcon/cphalcon/wiki/Generating-a-backtrace as reference

```php
Error: Call to undefined method stdClass::update()
#7 /app/controllers/FrontendController.php(450): unsubSubmitAction
#6 [Anonymous function](0): callActionMethod
#5 [Anonymous function](0): _dispatch
#4 [Anonymous function](0): dispatch
#3 [Anonymous function](0): handle
#2 /app/library/Bootstrap.php(130): getOutput
#1 /app/library/Bootstrap.php(119): run
#0 /public/index.php(12): null
```
> Provide minimal script to reproduce the issue

```php
// the model query
Subscribers::findFirst([
            'conditions' => 'email_hash = :email_hash: AND is_deleted=0 AND status!=:status:',
            'bind' => [
                'email_hash' => $hash_email,
                'status' => Subscribers::UNSUBSCRIBE
            ]
        ]);
```
### Details

* Phalcon version: 3.0.3
* PHP Version: PHP 7.0.16 (built: Feb 22 2017 20:55:04) ( NTS )
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with the ionCube PHP Loader (enabled) + Intrusion Protection from ioncube24.com (unconfigured) v6.0.4, Copyright (c) 2002-2016, by ionCube Ltd.
    with Zend OPcache v7.0.16, Copyright (c) 1999-2017, by Zend Technologies
    with Xdebug v2.5.1, Copyright (c) 2002-2017, by Derick Rethans
* Operating System: Centos 7.2, Minimal installation
* Installation type: Compiling from source 
* Server: Litespeed
* Other related info (Database, table schema): Database : MySql/MariaDB

**Comment by Jurigag** [comment]
Need script to reproduce, post full code of your model, controller, schema etc

**Comment by gamalan** [comment]
I call the update method in my controller but it doesn't exist, hence the stack trace. Here is the code(Not full, but part of it).

```php
public function unsubSubmit(){
     $email_hash = $this->dispatcher->getParam("hash");
     $token = $this->dispatcher->getParam("hash");
     $form = $this->form->getByToken($token);
     $subscriber = $this->tracks->getSubscriberByHashAndUserGUID($form->user_guid, $email_hash);
     try{
          $subscriber->status = "unsubscribed";
          $subscriber->update();
     }catch(Throwable $e){
          //logging
     }
}
``` 

```php
//Class Tracks
public function getSubscriberByHashAndUserGUID($user_guid,$hash_email){
        return Subscribers::findFirst([
            'conditions' => 'user_guid = :user_guid: AND email_hash = :email_hash: AND is_deleted=0 AND status!=:status:',
            'bind' => [
                'user_guid' => $user_guid,
                'email_hash' => $hash_email,
                'status' => Subscribers::UNSUBSCRIBE
            ]
        ]);
    }

```

```php
class Subscribers extends BaseModel
{

    public $timestamp = TRUE;
    public $userstamp = TRUE;
    public $softdelete = TRUE;
    //
    public $id;
    public $full_name;
    public $email;
    public $status;
    public $tag;
    public $ip_address;
    public $soft_bounces;
    public $hard_bounces;

    CONST STATUS_VALUE = [
        'subscribed' => 'Subscribed',
        'unsubscribed' => 'Unsubscribed',
        'unconfirmed' => 'Unconfirmed',
    ];

    const SUBSCRIBED = 'subscribed';
    const UNSUBSCRIBE = 'unsubscribed';
    const UNCONFIRM = 'unconfirmed';
    const BOUNCE = 'bounced';

    public function getSource()
    {
        return 'subscriber';
    }

    public function initialize()
    {
        $this->hasMany('id', 'Models\SubscriberLists', 'subscriber_id', [
            'alias' => 'subscriberLists'
        ]);
        $this->hasMany('id', 'Models\SubscriberTags', 'subscriber_id', [
            'alias' => 'subscriberTags'
        ]);

        $this->allowEmptyStringValues([
            'full_name'
        ]);
    }
}
```

```php
class BaseModel extends Model {
	public $timestamp = FALSE;
	public $userstamp = FALSE;
	public $softdelete = FALSE;
	//
	public $user_guid;
	public $is_deleted;
	public $created_at;
	public $modified_at;
	public $deleted_at;

	public static function find($parameters = null) {
		return parent::find($parameters);
	}

	public static function findFirst($parameters = null) {
		return parent::findFirst($parameters);
	}

	public function beforeValidationOnCreate() {
		if ($this->timestamp) {
			$this->created_at = time();
			$this->modified_at = time();
		}
        if ($this->softdelete) {
            if(!isset($this->is_deleted)){
                $this->is_deleted = 0;
            }
            if(!isset($this->deleted_at)){
                $this->deleted_at = 0;
            }
        }
	}

	public function beforeValidationOnUpdate() {
		if ($this->timestamp && empty($this->is_deleted)) {
			$this->modified_at = time();
		} else {
			$this->deleted_at = time();
		}
	}

	public function softdelete() {
		$this->is_deleted = 1;
		$this->update();
	}


	public static function allRecordsByUser($guid) {
		return self::find([
					'is_deleted = :is_deleted: AND user_guid = :user_guid:',
					'bind' => [
						'is_deleted' => 0,
						'user_guid' => $guid
					],
		]);
	}

	public static function findById($id,$guid=null) {
		$where = 'is_deleted = :is_deleted: AND id = :id:';
		$bind = [
			'is_deleted' => 0,
			'id' => $id
		];
		
		if (!is_null($guid)) {
			$where .= ' AND user_guid = :user_guid:';
			$bind['user_guid'] = $guid;
		}
		
		return self::findFirst([
					$where,
					'bind' => $bind,
		]);
	}

}
```

**Comment by Jurigag** [comment]
Table schema is need too, also best will be to create some repo to reproduce a problem.
