### ISSUE TITLE
The argument is not initialized or iterable() - Saving related records

### ISSUE THREAD

**Issue by aat2703** [phalcon/cphalcon#12995]
This error comes up when saving related PaymentLines... I'm clueless... 

## Error: 
```
PHP Fatal error:  Uncaught Exception: The argument is not initialized or iterable() in phalcon/mvc/model.zep:2897
Stack trace:
#0 [internal function]: Phalcon\\Mvc\\Model->_postSaveRelatedRecords(Object(Phalcon\\Db\\Adapter\\Pdo\\Mysql), Array)
#1 [internal function]: Phalcon\\Mvc\\Model->save(NULL, NULL)
#2 /var/www/modules/development/webroot/api/v7/models/Restaurant/ViewModel/Payment/PaymentsView.php(314): Phalcon\\Mvc\\Model->update()
#3 /var/www/modules/development/webroot/api/v7/library/ManualEntry/ManualEntry.php(114): Restaurant\\ViewModel\\Payment\\PaymentsView->createPayments(Array, 3177)
#4 /var/www/modules/development/webroot/api/v7/controllers/OrderLink/OrderLinkApiController.php(61): ManualEntry\\ManualEntry->createManualEntryMultiple(Array)
#5 [internal function]: OrderLinkApiController->create_orderlinks()
#6 [internal function]: Phalcon\\Mvc\\Micro\\LazyLoader->__call('create_orderlin...', Array)
#7 [internal function]: Phalcon\\Mvc\\Micro\\LazyLoader->callMethod('create_orderlin...', Array, NULL)
#8 /var/www/modules/development/ in phalcon/mvc/model.zep on line 2897
```
## Code to reproduce

```php
 foreach($payments as $dataPayment):

     $conditions = array(
         'conditions' => 'orderLinkID = :orderLinkID: AND personNumber = :personNumber:',
         'bind'       => array(
             'orderLinkID'   => $orderLinkID,
             'personNumber'  => $dataPayment['personNumber']
         )
     );

     $payment = RestaurantPayments::findFirst($conditions);

     if($payment && $payment->state == PaymentsView::PAYMENT_PENDING):

         $payment->identifier = isset($dataPayment['identifier']) ? $dataPayment['identifier'] : null;
         $payment->discount   = isset($dataPayment['discount']) ? $dataPayment['discount'] : 0;

         $lines = [];

         if(DataValidator::is_valid_array_validator($dataPayment['paymentLines'])):

             foreach($dataPayment['paymentLines'] as $paymentLine):

                 $RestaurantPaymentLines = new RestaurantPaymentLines();

                 $paymentLine['customerPaidAmount']  = Number::number_format_amount($paymentLine['customerPaidAmount']);
                 $paymentLine['discount']            = Number::number_format_amount($paymentLine['discount']);

                 $model = $RestaurantPaymentLines->assign(
                     $paymentLine,
                     null,
                     [
                         'customerPaidAmount',
                         'discount',
                         'currency',
                         'identifier',
                         'paymentTypeID'
                     ]
                 );

                 $lines[] = $model;

             endforeach;

             $payment->PaymentLines = $lines;

         endif;

         $payment->update();

     endif;

     if(!$payment):

        if(!is_numeric($dataPayment['personNumber'])):
            $dataPayment['personNumber'] = 0;
        endif;

         $RestaurantPayments = new RestaurantPayments();

         $RestaurantPayments->orderLinkID  = $orderLinkID;
         $RestaurantPayments->personNumber = $dataPayment;
         $RestaurantPayments->state        = PaymentsView::PAYMENT_PENDING;
         $RestaurantPayments->identifier   = $dataPayment['identifier'];
         $RestaurantPayments->discount     = $dataPayment['discount']; // TODO Thomas to send in oere

         $RestaurantPayments->create();

     endif;

 endforeach;
```
### Details

phalcon => enabled
Author => Phalcon Team and contributors
Version => 3.2.0
Build Date => Jul  6 2017 13:36:21
Powered by Zephir => Version 0.9.8-6335775f25

Directive => Local Value => Master Value
phalcon.db.escape_identifiers => On => On
phalcon.db.force_casting => Off => Off
phalcon.orm.events => On => On
phalcon.orm.virtual_foreign_keys => On => On
phalcon.orm.column_renaming => On => On
phalcon.orm.not_null_validations => On => On
phalcon.orm.exception_on_failed_save => Off => Off
phalcon.orm.enable_literals => On => On
phalcon.orm.late_state_binding => Off => Off
phalcon.orm.enable_implicit_joins => On => On
phalcon.orm.cast_on_hydrate => Off => Off
phalcon.orm.ignore_unknown_columns => Off => Off
phalcon.orm.update_snapshot_on_save => On => On
phalcon.orm.disable_assign_setters => Off => Off

PHP 7.1.7-1+ubuntu14.04.1+deb.sury.org+1 (cli) (built: Jul  7 2017 10:07:42) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.1.7-1+ubuntu14.04.1+deb.sury.org+1, Copyright (c) 1999-2017, by Zend Technologies

* Operating System: Ubuntu 14.04
* Installation type: Compiling from source
* Server: Apache 
* Database: AWS RDS - MySQL

**Comment by aat2703** [comment]
This works now (After a lot of optimizations in the project)... I'll try to find out what went wrong...

**Comment by FubuBy** [comment]
Did you find what went wrong?
