### ISSUE TITLE
Segmentation fault in getPropertiesAnnotations

### ISSUE THREAD

**Issue by vGhost2000** [phalcon/cphalcon#13185]
### Expected and Actual Behavior

for reproduce simple way use this image:
docker run --rm -it mileschou/phalcon:7.1-alpine /bin/sh
Create file example.php with code:
```php
<?php

use \Phalcon\Mvc\Model;
use Phalcon\Forms\Form;
use Phalcon\DI\FactoryDefault;

class MyComponent extends Model
{
    /**
     * @validation(Phalcon\Forms\Element\Text, [PresenceOf, StringLength: [min: 3, max: 200]])
     */
    public $entry_price;


    /**
     *            THIS IS A PROBLEM, in {at} without text:
     * @
     */
    public $description;
}

class BaseForm extends Form
{
    public function __construct($model, array $fields = array())
    {
        var_dump($this->annotations->get($model)->getPropertiesAnnotations());
    }
}
$di = new FactoryDefault;
new BaseForm(new MyComponent($di));
```

And run `php example.php`

### Details

```
@e7d158d6d978:/tmp$ php ./example.php
Segmentation fault


@e7d158d6d978:/tmp$ uname -a
Linux e7d158d6d978 4.9.32-0-virthardened #1-Alpine SMP Fri Jun 16 12:39:17 GMT 2017 x86_64 Linux


@e7d158d6d978:/tmp$ php -v
PHP 7.1.11 (cli) (built: Nov  4 2017 10:34:59) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies


@e7d158d6d978:/tmp$ php --ri phalcon

phalcon


Web framework delivered as a C-extension for PHP
phalcon => enabled
Author => Phalcon Team and contributors
Version => 3.2.4
Build Date => Nov 25 2017 07:48:38
Powered by Zephir => Version 0.10.4-11e39849b0

Directive => Local Value => Master Value
phalcon.db.escape_identifiers => On => On
phalcon.db.force_casting => Off => Off
phalcon.orm.events => On => On
phalcon.orm.virtual_foreign_keys => On => On
phalcon.orm.column_renaming => On => On
phalcon.orm.not_null_validations => On => On
phalcon.orm.exception_on_failed_save => Off => Off
phalcon.orm.enable_literals => On => On
phalcon.orm.late_state_binding => Off => Off
phalcon.orm.enable_implicit_joins => On => On
phalcon.orm.cast_on_hydrate => Off => Off
phalcon.orm.ignore_unknown_columns => Off => Off
phalcon.orm.update_snapshot_on_save => On => On
phalcon.orm.disable_assign_setters => Off => Off
```

* Installation type: Compiling from this source https://github.com/phalcon/cphalcon/archive/v3.2.4.tar.gz
* Server: Nginx + php-fpm / php-cli
* unix line brakes in php file

**Comment by Jurigag** [comment]
I added var_dump in zephir to find what might be wrong:

```
zephir_memory_restore_stack_common: observed variable #7 (0x7fffffffa020) has too many references (4035453313), type=7  [(null)]
#0  0x7fffe8136cec [/root/.phpbrew/php/php-7.1.1/lib/php/extensions/debug-non-zts-20160303/phalcon.so(zephir_print_backtrace+0x2b) [0x7fffe8136cec]]
#1  0x7fffe8134f42 [/root/.phpbrew/php/php-7.1.1/lib/php/extensions/debug-non-zts-20160303/phalcon.so(+0x7558f42) [0x7fffe8134f42]]
#2  0x7fffe8135045 [/root/.phpbrew/php/php-7.1.1/lib/php/extensions/debug-non-zts-20160303/phalcon.so(zephir_memory_restore_stack+0xfa) [0x7fffe8135045]]
#3  0x7fffe82284e1 [/root/.phpbrew/php/php-7.1.1/lib/php/extensions/debug-non-zts-20160303/phalcon.so(zim_Phalcon_Annotations_Reader_parse+0x197c) [0x7fffe82284e1]]
#4  0x9e4e16 [/root/.phpbrew/php/php-7.1.1/bin/php(zend_call_function+0xae2) [0x9e4e16]]
#5  0x7fffe814322f [/root/.phpbrew/php/php-7.1.1/lib/php/extensions/debug-non-zts-20160303/phalcon.so(zephir_call_user_function+0x5f8) [0x7fffe814322f]]
#6  0x7fffe81437ee [/root/.phpbrew/php/php-7.1.1/lib/php/extensions/debug-non-zts-20160303/phalcon.so(zephir_call_class_method_aparams+0x128) [0x7fffe81437ee]]
#7  0x7fffe816cc84 [/root/.phpbrew/php/php-7.1.1/lib/php/extensions/debug-non-zts-20160303/phalcon.so(zim_Phalcon_Annotations_Adapter_get+0x6cc) [0x7fffe816cc84]]
#8  0xa5df3f [/root/.phpbrew/php/php-7.1.1/bin/php() [0xa5df3f]]
#9  0xa5c3a4 [/root/.phpbrew/php/php-7.1.1/bin/php(execute_ex+0x49) [0xa5c3a4]]
#10  0xa5c4b6 [/root/.phpbrew/php/php-7.1.1/bin/php(zend_execute+0xf3) [0xa5c4b6]]
#11  0x9fcdde [/root/.phpbrew/php/php-7.1.1/bin/php(zend_execute_scripts+0x17b) [0x9fcdde]]
#12  0x96677c [/root/.phpbrew/php/php-7.1.1/bin/php(php_execute_script+0x452) [0x96677c]]
#13  0xaddd41 [/root/.phpbrew/php/php-7.1.1/bin/php() [0xaddd41]]
#14  0xadef05 [/root/.phpbrew/php/php-7.1.1/bin/php() [0xadef05]]
#15  0x7ffff5772f45 [/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf5) [0x7ffff5772f45]]
#16  0x434d59 [/root/.phpbrew/php/php-7.1.1/bin/php() [0x434d59]]

array(1) {
  [0]=>
  array(5) {
    ["type"]=>
    int(300)
    ["name"]=>
    string(10) "validation"
    ["arguments"]=>
    array(2) {
      [0]=>
      array(1) {
        ["expr"]=>
        array(2) {
          ["type"]=>
          int(307)
          ["value"]=>
          string(26) "Phalcon\Forms\Element\Text"
        }
      }
      [1]=>
      array(1) {
        ["expr"]=>
        array(2) {
          ["type"]=>
          int(308)
          ["items"]=>
          array(2) {
            [0]=>
            array(1) {
              ["expr"]=>
              array(2) {
                ["type"]=>
                int(307)
                ["value"]=>
                string(10) "PresenceOf"
              }
            }
            [1]=>
            array(2) {
              ["expr"]=>
              array(2) {
                ["type"]=>
                int(308)
                ["items"]=>
                array(2) {
                  [0]=>
                  array(2) {
                    ["expr"]=>
                    array(2) {
                      ["type"]=>
                      int(301)
                      ["value"]=>
                      string(1) "3"
                    }
                    ["name"]=>
                    string(3) "min"
                  }
                  [1]=>
                  array(2) {
                    ["expr"]=>
                    array(2) {
                      ["type"]=>
                      int(301)
                      ["value"]=>
                      string(3) "200"
                    }
                    ["name"]=>
                    string(3) "max"
                  }
                }
              }
              ["name"]=>
              string(12) "StringLength"
            }
          }
        }
      }
    }
    ["file"]=>
    string(21) "/vagrant/www/test.php"
    ["line"]=>
    int(4294967295)
  }
}

Program received signal SIGSEGV, Segmentation fault.
0x0000000000a0d4a9 in zval_get_type (pz=0x6d726f465c6e6f63) at /root/.phpbrew/build/php-7.1.1/Zend/zend_types.h:332
332             return pz->u1.v.type;
(gdb) bt
#0  0x0000000000a0d4a9 in zval_get_type (pz=0x6d726f465c6e6f63) at /root/.phpbrew/build/php-7.1.1/Zend/zend_types.h:332
#1  0x0000000000a0e9ca in zend_array_recalc_elements (ht=0x7ffff0882080) at /root/.phpbrew/build/php-7.1.1/Zend/zend_hash.c:281
#2  0x0000000000a0ea6a in zend_array_count (ht=0x7ffff0882080) at /root/.phpbrew/build/php-7.1.1/Zend/zend_hash.c:297
#3  0x000000000089ae3d in php_var_dump (struc=0x7ffff0814390, level=1) at /root/.phpbrew/build/php-7.1.1/ext/standard/var.c:127
#4  0x00007fffe8152257 in zephir_var_dump (var=0x7ffff0814390) at /root/my-cphalcon/ext/kernel/variables.c:43
#5  0x00007fffe8223dfe in zim_Phalcon_Annotations_Collection___construct (execute_data=0x7ffff0814340, return_value=0x7fffffffa310)
    at /root/my-cphalcon/ext/phalcon/annotations/collection.zep.c:86
#6  0x00000000009e4e16 in zend_call_function (fci=0x7fffffffa360, fci_cache=0x7fffffffa330) at /root/.phpbrew/build/php-7.1.1/Zend/zend_execute_API.c:842
#7  0x00007fffe814322f in zephir_call_user_function (object_pp=0x7fffffffa710, obj_ce=0x161c0f0, type=zephir_fcall_method, function_name=0x7fffffffa570, retval_ptr=0x0,
    cache_entry=0x7fffffffa5e0, cache_slot=12, param_count=1, params=0x7fffffffa5d0) at /root/my-cphalcon/ext/kernel/fcall.c:387
#8  0x00007fffe81437ee in zephir_call_class_method_aparams (return_value=0x0, ce=0x161c0f0, type=zephir_fcall_method, object=0x7fffffffa710,
    method_name=0x7fffe8942e38 "__construct", method_len=11, cache_entry=0x7fffffffa5e0, cache_slot=12, param_count=1, params=0x7fffffffa5d0)
    at /root/my-cphalcon/ext/kernel/fcall.c:522
#9  0x00007fffe822a470 in zim_Phalcon_Annotations_Reflection_getPropertiesAnnotations (execute_data=0x7ffff08142f0, return_value=0x7fffffffa750)
    at /root/my-cphalcon/ext/phalcon/annotations/reflection.zep.c:237
#10 0x0000000000a5d9ae in ZEND_DO_FCALL_SPEC_RETVAL_UNUSED_HANDLER () at /root/.phpbrew/build/php-7.1.1/Zend/zend_vm_execute.h:970
#11 0x0000000000a5c3a4 in execute_ex (ex=0x7ffff0814030) at /root/.phpbrew/build/php-7.1.1/Zend/zend_vm_execute.h:429
#12 0x0000000000a5c4b6 in zend_execute (op_array=0x7ffff0885000, return_value=0x0) at /root/.phpbrew/build/php-7.1.1/Zend/zend_vm_execute.h:474
#13 0x00000000009fcdde in zend_execute_scripts (type=8, retval=0x0, file_count=3) at /root/.phpbrew/build/php-7.1.1/Zend/zend.c:1474
#14 0x000000000096677c in php_execute_script (primary_file=0x7fffffffcd00) at /root/.phpbrew/build/php-7.1.1/main/main.c:2537
#15 0x0000000000addd41 in do_cli (argc=2, argv=0x1407380) at /root/.phpbrew/build/php-7.1.1/sapi/cli/php_cli.c:993
#16 0x0000000000adef05 in main (argc=2, argv=0x1407380) at /root/.phpbrew/build/php-7.1.1/sapi/cli/php_cli.c:1381
```
