### ISSUE TITLE
Select with no options doesnt render

### ISSUE THREAD

**Issue by rover95x** [phalcon/cphalcon#13352]
### Expected and Actual Behavior

I wish to render a SELECT form input with no options. The error given is:
" Invalid data provided to SELECT helper ", which from the source code, stems from this file:
[Phalcon\Tag\Select.zep](https://github.com/phalcon/cphalcon/blob/master/phalcon/tag/select.zep)

From my little understanding of C, it seems, that there is no check, if there are in fact any options given in the first place, which should be possible, given the function definition in:
[Phalcon\Forms\Element\Select.zep](https://github.com/phalcon/cphalcon/blob/master/phalcon/forms/element/select.zep)

I've tried omitting it and setting the $data to null. Neither works

Backtrace:
```php
Invalid data provided to SELECT helper
#0 [internal function]: Phalcon\Tag\Select::selectField(Array, NULL)
#1 [internal function]: Phalcon\Forms\Element\Select->render(NULL)
#2 /home/vagrant/workspace/HomeApp/cache/volt/%%home%%vagrant%%workspace%%homeapp%%app%%views%%layouts%%fooddata.volt.php(92): Phalcon\Forms\Form->render('foodGroupId')
#3 [internal function]: unknown()
#4 [internal function]: Phalcon\Mvc\View\Engine\Volt->render('/home/vagrant/w...', Array, true)
#5 [internal function]: Phalcon\Mvc\View->_engineRender(Array, 'layouts/FoodDat...', true, true, NULL)
#6 [internal function]: Phalcon\Mvc\View->render('FoodData', 'index')
#7 /home/vagrant/workspace/HomeApp/public/index.php(45): Phalcon\Mvc\Application->handle()
#8 {main}
```

```php
// form base class
class FormBase extends Form
{
    final public function createSelect( string $name , string $label , $data = null ) : Select
    {
        //  condition for testing purposes
        if ( is_null ( $data ) )
        {
            $select = new Select ( $name );
        }
        else
        {
            $select = new Select ( $name , $data );
        }

        $select->setLabel( $label );

        $select->clear();

        return $select;
    }

    final public function handleAttributes( array $attributes )
    {
        $this->checkElementsExistance ( array_keys ( $attributes ) );

        foreach ( $attributes as $elementName => $attributes )
        {
            foreach( $attributes as $attributeName => $value )
            {
                $this->get ( $elementName )->setAttribute ( $attributeName , $value );
            }
        }
    }

    private function checkElementsExistance( array $elementNames )
    {
        foreach( $elementNames as $elementName )
        {
            if ( $this->has ( $elementName ) == false )
            {
                throw new Exception( 'The element ' . $elementName . ' could not be found in the form' );
            }
        }
    }
}

// Form Class

final class AddEdit extends \HomeApp\Forms\FormBase
{
   function initialize ( $entity = null , $options = null )
    {
       $attributes = array( 'selectTest'     => [ 'class' => 'form-control homeselect' , 'useEmpty'   => true , 'emptyText'  => 'test' , 'emptyValue' => '' ]  );

       $this->add ( $this->createSelect ( 'selectTest' , 'labelTest'  ) );
       $this->handleAttributes ( $attributes );
    }
}

// In the view
<div class="form-group">
   {{ addFoodForm.label('selectTest') }}
   {{ addFoodForm.render('selectTest') }}
</div>

```
### Details

* Phalcon version: 3.3.2
* PHP Version: 7.1.16
* Operating System: Vagrant Phalcon Box
* Server: Nginx

**Comment by rover95x** [comment]
I'm aware it can't be empty.

I was trying to point out the discrepancy between the function definition in the select form class, in which the option parameter is optional and thus can be set to null, and the function definition in the tag element, in which the option paramater is required. 

Since rendering a form is a possibility, keeping that nuance in mind, is a slight annoyance. Naturally, this is not a show-stopper, as it can be easily cirumvented.

I guess there are several options:
- change the function definition in the form select class
- change the render behaviour of a select
- change nothing, but update the documentation reflecting that if one wishes to render a form with a select, it needs to have options supplied to it.
