### ISSUE TITLE
Uncaught Error: Access to undeclared static property: Phalcon\Di::$_default

### ISSUE THREAD

**Issue by leslie5803** [phalcon/cphalcon#13373]
there was an ajax took a long time because php executed allowed memory size exhausted, bofore allowed memory size exhausted throwed refresh the web page, and u'll get the follow error every time:

```
Fatal error: Uncaught Error: Access to undeclared static property: Phalcon\Di::$_default 
in E:\sites\audi\config\services.php:19
Stack trace:
#0 [internal function]: Phalcon\Di->__construct() 
#1 E:\sites\audi\config\services.php(19): Phalcon\Di\FactoryDefault->__construct() 
#2 E:\sites\audi\public\index.php(26): require('E:\\sites\\audi\\c...') 
#3 {main} 

Next Error: Access to undeclared static property: Phalcon\Di::$_default 
in E:\sites\audi\config\services.php:19 
Stack trace: 
#0 [internal function]: Phalcon\Di->__construct() 
#1 E:\sites\audi\config\services.php(19): Phalcon\Di\FactoryDefault->__construct() 
#2 E:\sites\audi\public\index.php(26): require('E:\\sites\\audi\\c...') 
#3 {main} thrown in E:\sites\audi\config\services.php on line 19
```

my enviroment is wampserver, wamp version is 3.1.3 64bit

**Comment by sergeyklay** [comment]
Refs: https://github.com/phalcon/cphalcon/issues/12056
