### ISSUE TITLE
extends class not working on Phalcon-4.0.0 and PHP-7.3

### ISSUE THREAD

**Issue by nagaho** [phalcon/cphalcon#13703]
``` bash
$ php -r 'class SampleConfig extends \Phalcon\Config{}'
terminated by signal SIGSEGV (Address boundary error)

$ php -v
PHP 7.3.0 (cli) (built: Dec  7 2018 11:00:11) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.0-dev, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.0, Copyright (c) 1999-2018, by Zend Technologies

$ php --ri phalcon
phalcon
Web framework delivered as a C-extension for PHP
phalcon => enabled
Author => Phalcon Team and contributors
Version => 4.0.0-alpha1
Build Date => Dec 25 2018 19:18:44
Powered by Zephir => Version 0.11.8-4495e75

Directive => Local Value => Master Value
phalcon.db.escape_identifiers => On => On
phalcon.db.force_casting => Off => Off
phalcon.orm.events => On => On
phalcon.orm.virtual_foreign_keys => On => On
phalcon.orm.column_renaming => On => On
phalcon.orm.not_null_validations => On => On
phalcon.orm.exception_on_failed_save => Off => Off
phalcon.orm.enable_literals => On => On
phalcon.orm.late_state_binding => Off => Off
phalcon.orm.enable_implicit_joins => On => On
phalcon.orm.cast_on_hydrate => Off => Off
phalcon.orm.ignore_unknown_columns => Off => Off
phalcon.orm.update_snapshot_on_save => On => On
phalcon.orm.disable_assign_setters => Off => Off
phalcon.orm.case_insensitive_column_map => Off => Off

(gdb) bt
#0  0x000055c0e03fa49c in zend_do_inheritance ()
#1  0x000055c0e039fb55 in do_bind_inherited_class ()
#2  0x000055c0e039fc9a in ?? ()
#3  0x000055c0e03afb0f in ?? ()
#4  0x000055c0e0387e6d in ?? ()
#5  0x000055c0e0389a18 in compile_string ()
#6  0x000055c0e03b3418 in zend_eval_stringl ()
#7  0x000055c0e03b3639 in zend_eval_stringl_ex ()
#8  0x000055c0e045121a in ?? ()
#9  0x000055c0e0013309 in ?? ()
#10 0x00007f71d45bb2e1 in __libc_start_main (main=0x55c0e0012ea0, argc=3, argv=0x7ffec4599e58, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7ffec4599e48) at ../csu/libc-start.c:291
#11 0x000055c0e00139ca in _start ()
```

**Comment by jturbide** [comment]
got the same issue +1

**Comment by nagaho** [comment]
@niden

```
$ php -r 'class SampleConfig extends \Phalcon\Config{}'
'php -r 'class SampleConfig ex...' terminated by signal SIGSEGV (Address boundary error)


$ php --ri phalcon
phalcon
Web framework delivered as a C-extension for PHP
phalcon => enabled
Author => Phalcon Team and contributors
Version => 4.0.0-alpha.2
Build Date => Feb  6 2019 17:37:16
Powered by Zephir => Version 0.11.9-209fe3f

Directive => Local Value => Master Value
phalcon.db.escape_identifiers => On => On
phalcon.db.force_casting => Off => Off
phalcon.orm.events => On => On
phalcon.orm.virtual_foreign_keys => On => On
phalcon.orm.column_renaming => On => On
phalcon.orm.not_null_validations => On => On
phalcon.orm.exception_on_failed_save => Off => Off
phalcon.orm.enable_literals => On => On
phalcon.orm.late_state_binding => Off => Off
phalcon.orm.enable_implicit_joins => On => On
phalcon.orm.cast_on_hydrate => Off => Off
phalcon.orm.ignore_unknown_columns => Off => Off
phalcon.orm.update_snapshot_on_save => On => On
phalcon.orm.disable_assign_setters => Off => Off
phalcon.orm.case_insensitive_column_map => Off => Off
```

**Comment by niden** [comment]
This cannot be reproduced with 7.2. So it should be related to PHP 7.3. 

/cc @sergeyklay

**Comment by jturbide** [comment]
Yes I can confirm, 7.3 only

**Comment by sergeyklay** [comment]
I'll try to sort out ASAP

**Comment by dreamsxin** [comment]
PHP 7.3.3 will fix the bug.
See https://github.com/php/php-src/commit/03384cae3c46254ccfd5d703b408a0f1d011ee3c#diff-9760ee109b1c5922071fac1e19d117df
```c
			if (CE_STATIC_MEMBERS(parent_ce) == NULL) {
				zend_class_init_statics(parent_ce);
			}
```

**Comment by sergeyklay** [comment]
I'm closing this issue but if I have made an oversight, please do get back in touch. Thanks
