### ISSUE TITLE
How to set PDO::ATTR_STRINGIFY_FETCHES to false when database is postgresql?

### ISSUE THREAD

**Issue by hks2002** [phalcon/cphalcon#13773]
postgresql dbconfig doesn't support  options like mysql in phalcon, how to set PDO::ATTR_STRINGIFY_FETCHES to false?

**Comment by hks2002** [comment]
PDO has a method setAttribute, does't phalcon have this also? I didn't see it in the API.

**Comment by hks2002** [comment]
My config.php is
```
return new \Phalcon\Config([
                           'database' => [
                               'adapter'     => 'Postgresql',
                               'host'        => 'localhost',
                               'username'    => 'postgres',
                               'password'    => '',
                               'dbname'      => 'timetrack',
                               'options'     => [    'ATTR_STRINGIFY_FETCHES' => false]
                           ],
                           'application' => [
                               'baseUri'        => '/',
                               'appDir'         => APP_PATH . '/',
                               'controllersDir' => APP_PATH . '/controllers/',
                               'modelsDir'      => APP_PATH . '/models/',
                               'viewsDir'       => APP_PATH . '/views/',
                               'cacheDir'       => BASE_PATH . '/cache/'
                           ],
                           'password' => [
                                'normal'     => '123',
                                'power'      => '321'
                           ],
                           'isInDev'      => true,
                           'defaultCurrencyRate' => 6.7
                           ]);
```
and In my services.php is 
```
$di->setShared('db', function() {
    $config = $this->getConfig();
        
    $class = 'Phalcon\Db\Adapter\Pdo\\' . $config->database->adapter;
    $connection = new $class([
                             'host'     => $config->database->host,
                             'username' => $config->database->username,
                             'password' => $config->database->password,
                             'dbname'   => $config->database->dbname,
                             'options'  => $config->database->options
                             ]);
    return $connection;
});
```
After I add this options, errors comes out:
```
2019/01/20 18:51:31 [error] 260#7116: *2041 FastCGI sent in stderr: "The argument is not initialized or iterable()
#0 [internal function]: Phalcon\Db\Adapter\Pdo->connect(Array)
#1 [internal function]: Phalcon\Db\Adapter\Pdo\Postgresql->connect(Array)
#2 D:\GitHub\TimeTrack\app\config\services.php(76): Phalcon\Db\Adapter\Pdo->__construct(Array)
#3 [internal function]: Closure->{closure}()
#4 [internal function]: Phalcon\Di\Service->resolve(NULL, Object(Phalcon\Di\FactoryDefault))
#5 [internal function]: Phalcon\Di->get('db', NULL)
#6 [internal function]: Phalcon\Di->getShared('db')
#7 D:\GitHub\TimeTrack\app\controllers\DataController.php(213): Phalcon\Di\Injectable->__get('db')
#8 [internal function]: DataController->soCountAction()
#9 [internal function]: Phalcon\Dispatcher->callActionMethod(Object(DataController), 'soCountAction', Array)
#10 [internal function]: Phalcon\Dispatcher->dispatch()
#11 D:\GitHub\TimeTrack\public\index.php(32): Phalcon\Mvc\Application->handle()
#12 {main}" while reading response header from upstream, client: 127.0.0.1, server: 127.0.0.1, request: "GET /data/soCount?Range=ByMonthThisYear HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "127.0.0.1", referrer: "http://127.0.0.1/"
```

**Comment by TimurFlush** [comment]
I do not recommend working with ORM/PHQL with this option, but I would be very interested to take a look at your database queries.

**Comment by hks2002** [comment]
I am using  raw sql:
```
         $sql = "SELECT 
                   soi.request_date,
                   soi.pn,
                   soi.pn_desc,
                   soi.pn_desc2,
                   soi.pn_desc3,
                   soi.qty,
                   round(soi.item_value),
                   so.currency
                 FROM 
                   sales_order_item as soi 
                 JOIN 
                   sales_order as so 
                 ON 
                   soi.so_code = so.so_code 
                 WHERE 
                   soi.request_date < (current_date + interval '1 year')
                   AND 
                   soi.request_date > (current_date - interval '1 month')
                   AND 
                   so.so_type = :so_type";
                   
        $stament = $this->db->prepare($sql);
        $stament->execute([':so_type'=>'NOR']);
        $output['nor'] = $stament->fetchAll(Phalcon\DB::FETCH_NUM);
```

**Comment by TimurFlush** [comment]
Then you want to say that with the option ATTR_STRINGIFY_FETCHES you get the error?

**Comment by hks2002** [comment]
Yes, you can understand it as you said.

**Comment by TimurFlush** [comment]
@niden what the fuck?

**Comment by hks2002** [comment]
Sorry, In my memory, I remember that,  when I try to use ORM/PHQL to get a record from database, options doesn't work by setting the db config.

**Comment by TimurFlush** [comment]
@niden try to say with Niden,
