### ISSUE TITLE
[BUG]: The formatted message is not valid

### ISSUE THREAD

**Issue by Jeckerson** [phalcon/cphalcon#14522]
**Describe the bug**
Impossible to pass log message as string, nor as array with `Logger->log()` method.

**To Reproduce**

**Example 1:**
```php
<?php

use Phalcon\Logger;
use Phalcon\Logger\Adapter\Syslog;
use Phalcon\Logger\Formatter\Line as LineFormatter;

$formatter = new LineFormatter("[devtools@localhost]: [%type%] %message%", 'D j H:i:s');
$adapter = new Syslog('php://stderr');
$adapter->setFormatter($formatter);

$logger = new Logger('messages', ['main' => $adapter]);
$logger->log(Logger::NOTICE, 'Notice message');
```

Produce error:
```plain
Uncaught Phalcon\Logger\Exception: The formatted message is not valid in phalcon/Logger/Adapter/Syslog.zep:107
Stack trace:
#0 [internal function]: Phalcon\Logger\Adapter\Syslog->process(Object(Phalcon\Logger\Item))
#1 [internal function]: Phalcon\Logger->addMessage(5, 'Notice message', Array)
#2 /srv/public/log_test.php(12): Phalcon\Logger->log(5, 'Notice message')
#3 {main}
  thrown in phalcon/Logger/Adapter/Syslog.zep on line 107
```

**Example 2:**

```php
// Try to pass as array, according example - https://docs.phalcon.io/4.0/en/logger#interpolation
$logger->log(Logger::NOTICE, [
    'type' => 'notice',
    'message' => 'Notice message',
]);
```

Produce error:
```plain
Array to string conversion
PHP message: PHP Fatal error:  Uncaught Phalcon\Logger\Exception: The formatted message is not valid in phalcon/Logger/Adapter/Syslog.zep:107
Stack trace:
#0 [internal function]: Phalcon\Logger\Adapter\Syslog->process(Object(Phalcon\Logger\Item))
#1 [internal function]: Phalcon\Logger->addMessage(5, 'Array', Array)
#2 /srv/public/log_test.php(13): Phalcon\Logger->log(5, Array)
#3 {main}
  thrown in phalcon/Logger/Adapter/Syslog.zep on line 107
```

<hr/>

**Expected behavior**
Log message into stderr without any fatal errors.

**Details**
 - Phalcon version: `4.0.0-rc.2`
 - PHP Version: `7.2.19`
 - Operating System: Ubuntu 18
 - Installation type: Compiling from source
 - Server: Nginx

**Comment by niden** [comment]
Resolved https://github.com/phalcon/cphalcon/pull/14525
