### ISSUE TITLE
\Phalcon\Mvc\Model setSchema broke insert and update from save()

### ISSUE THREAD

**Issue by zordon13** [phalcon/cphalcon#14531]
When call save() in model where in initialize call setSchema throws exception:
```
PHP Fatal error:  Uncaught PDOException: SQLSTATE[42P01]: Undefined table: 7 ERROR:  relation "Array" does not exist
```
### Example ###
```php <?php
require_once realpath(__DIR__) . '/../../../../../app/bootstrap.php';
$di->getDb()->execute('CREATE TABLE IF NOT EXISTS public.test_model(c1 text);');
class TestModel extends \Phalcon\Mvc\Model {
    public $c1;
    public function initialize()
    {
        $this->setSource("test_model");
    }                
};

class TestModelSchema extends \Phalcon\Mvc\Model {
    public $c1;
    public function initialize()
    {
        $this->setSource("test_model");
        $this->setSchema('public');
        
    }                
};

$inst = new TestModel();
$inst->c1 = 'fine';
$inst->save(); // inset ok

$inst2 = new TestModelSchema();
$inst2->c1 = 'bad';
$inst2->save(); //throw exception
```
Run script in cli:
```
php test.php
PHP Notice:  Array to string conversion in /home/user/workspace/site/app/modules/cli/queue/test/test.php on line 28

Notice: Array to string conversion in /home/user/workspace/site/app/modules/cli/queue/test/test.php on line 28
PHP Fatal error:  Uncaught PDOException: SQLSTATE[42P01]: Undefined table: 7 ERROR:  relation "Array" does not exist
LINE 1: INSERT INTO "Array" ("c1") VALUES ($1)
                    ^ in /home/user/workspace/site/app/modules/cli/queue/test/test.php:28
Stack trace:
#0 [internal function]: PDOStatement->execute()
#1 [internal function]: Phalcon\Db\Adapter\Pdo\AbstractPdo->executePrepared(Object(PDOStatement), Array, Array)
#2 [internal function]: Phalcon\Db\Adapter\Pdo\AbstractPdo->execute('INSERT INTO "Ar...', Array, Array)
#3 [internal function]: Phalcon\Db\Adapter\AbstractAdapter->insert(Array, Array, Array, Array)
#4 [internal function]: Phalcon\Mvc\Model->_doLowInsert(Object(Phalcon\Mvc\Model\MetaData\Redis), Object(Phalcon\Db\Adapter\Pdo\Postgresql), Array, false)
#5 /home/user/workspace/site/app/modules/cli/queue/test/test.php(28): Phalcon\Mvc\Model->save()
#6 {main}
  thrown in /home/user/workspace/site/app/modules/cli/queue/test/test.php on line 28

Fatal error: Uncaught PDOException: SQLSTATE[42P01]: Undefined table: 7 ERROR:  relation "Array" does not exist
LINE 1: INSERT INTO "Array" ("c1") VALUES ($1)
                    ^ in /home/user/workspace/site/app/modules/cli/queue/test/test.php:28
Stack trace:
#0 [internal function]: PDOStatement->execute()
#1 [internal function]: Phalcon\Db\Adapter\Pdo\AbstractPdo->executePrepared(Object(PDOStatement), Array, Array)
#2 [internal function]: Phalcon\Db\Adapter\Pdo\AbstractPdo->execute('INSERT INTO "Ar...', Array, Array)
#3 [internal function]: Phalcon\Db\Adapter\AbstractAdapter->insert(Array, Array, Array, Array)
#4 [internal function]: Phalcon\Mvc\Model->_doLowInsert(Object(Phalcon\Mvc\Model\MetaData\Redis), Object(Phalcon\Db\Adapter\Pdo\Postgresql), Array, false)
#5 /home/user/workspace/site/app/modules/cli/queue/test/test.php(28): Phalcon\Mvc\Model->save()
#6 {main}
  thrown in /home/user/workspace/site/app/modules/cli/queue/test/test.php on line 28
```
if disable service modelsMetadata (where i use Redis):
```
PHP Notice:  Array to string conversion in /home/user/workspace/site/app/modules/cli/queue/test/test.php on line 28

Notice: Array to string conversion in /home/user/workspace/site/app/modules/cli/queue/test/test.php on line 28
PHP Fatal error:  Uncaught PDOException: SQLSTATE[42P01]: Undefined table: 7 ERROR:  relation "Array" does not exist
LINE 1: INSERT INTO "Array" ("c1") VALUES ($1)
                    ^ in /home/user/workspace/site/app/modules/cli/queue/test/test.php:28
Stack trace:
#0 [internal function]: PDOStatement->execute()
#1 [internal function]: Phalcon\Db\Adapter\Pdo\AbstractPdo->executePrepared(Object(PDOStatement), Array, Array)
#2 [internal function]: Phalcon\Db\Adapter\Pdo\AbstractPdo->execute('INSERT INTO "Ar...', Array, Array)
#3 [internal function]: Phalcon\Db\Adapter\AbstractAdapter->insert(Array, Array, Array, Array)
#4 [internal function]: Phalcon\Mvc\Model->_doLowInsert(Object(Phalcon\Mvc\Model\MetaData\Memory), Object(Phalcon\Db\Adapter\Pdo\Postgresql), Array, false)
#5 /home/user/workspace/site/app/modules/cli/queue/test/test.php(28): Phalcon\Mvc\Model->save()
#6 {main}
  thrown in /home/user/workspace/site/app/modules/cli/queue/test/test.php on line 28

Fatal error: Uncaught PDOException: SQLSTATE[42P01]: Undefined table: 7 ERROR:  relation "Array" does not exist
LINE 1: INSERT INTO "Array" ("c1") VALUES ($1)
                    ^ in /home/user/workspace/site/app/modules/cli/queue/test/test.php:28
Stack trace:
#0 [internal function]: PDOStatement->execute()
#1 [internal function]: Phalcon\Db\Adapter\Pdo\AbstractPdo->executePrepared(Object(PDOStatement), Array, Array)
#2 [internal function]: Phalcon\Db\Adapter\Pdo\AbstractPdo->execute('INSERT INTO "Ar...', Array, Array)
#3 [internal function]: Phalcon\Db\Adapter\AbstractAdapter->insert(Array, Array, Array, Array)
#4 [internal function]: Phalcon\Mvc\Model->_doLowInsert(Object(Phalcon\Mvc\Model\MetaData\Memory), Object(Phalcon\Db\Adapter\Pdo\Postgresql), Array, false)
#5 /home/user/workspace/site/app/modules/cli/queue/test/test.php(28): Phalcon\Mvc\Model->save()
#6 {main}
  thrown in /home/user/workspace/site/app/modules/cli/queue/test/test.php on line 28
```

### Version ###
```
PHP 7.3.11 (cli) (built: Oct 26 2019 15:16:52) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.11, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.11, Copyright (c) 1999-2018, by Zend Technologies
```

```
php --ri phalcon
phalcon
Web framework delivered as a C-extension for PHP
phalcon => enabled
Author => Phalcon Team and contributors
Version => 4.0.0-rc.2
Build Date => Nov 13 2019 13:58:33
Powered by Zephir => Version 0.12.10-fedc314

Directive => Local Value => Master Value
phalcon.db.escape_identifiers => On => On
phalcon.db.force_casting => Off => Off
phalcon.orm.case_insensitive_column_map => Off => Off
phalcon.orm.cast_last_insert_id_to_int => Off => Off
phalcon.orm.cast_on_hydrate => Off => Off
phalcon.orm.column_renaming => On => On
phalcon.orm.disable_assign_setters => Off => Off
phalcon.orm.enable_implicit_joins => On => On
phalcon.orm.enable_literals => On => On
phalcon.orm.events => On => On
phalcon.orm.exception_on_failed_save => Off => Off
phalcon.orm.exception_on_failed_metadata_save => On => On
phalcon.orm.ignore_unknown_columns => Off => Off
phalcon.orm.late_state_binding => Off => Off
phalcon.orm.not_null_validations => On => On
phalcon.orm.update_snapshot_on_save => On => On
phalcon.orm.virtual_foreign_keys => On => On
phalcon.warning.enable => On => On```

**Comment by niden** [comment]
Resolved in https://github.com/phalcon/cphalcon/pull/14539
