### ISSUE TITLE
[BUG]: Documentation regarding initialization of the DB adaper is unclear and not complete

### ISSUE THREAD

**Issue by sergeyklay** [phalcon/cphalcon#14967]
```php
use Phalcon\Di;
use Phalcon\Di\FactoryDefault;
use Phalcon\Db\Adapter\PdoFactory;
use Phalcon\Mvc\Model;

$options = ['dbname' => '/tmp/local.db'];

Di::reset();

$container = new FactoryDefault();
Di::setDefault($container);

$container->setShared(
    'db',
    (new PdoFactory())->newInstance('sqlite', $options)
);

class Customer extends Model {}

$criteria = Customer::query();
$criteria->limit(20, 0);

var_dump($criteria->execute());
```

```
PHP Fatal error:  Uncaught RuntimeException: Trying to call method getrelationbyalias on a non-object in /tmp/test.php:16
Stack trace:
#0 [internal function]: Phalcon\Mvc\Model->__isset('oldSnapshot')
#1 [internal function]: Phalcon\Mvc\Model\Manager->load('Customer')
#2 [internal function]: Phalcon\Mvc\Model\Query->_prepareSelect()
#3 [internal function]: Phalcon\Mvc\Model\Query->parse()
#4 [internal function]: Phalcon\Mvc\Model\Query->execute()
#5 [internal function]: Phalcon\Mvc\Model::find(Array)
#6 /tmp/test.php(16): Phalcon\Mvc\Model\Criteria->execute()
#7 {main}
  thrown in /tmp/test.php on line 16

Fatal error: Uncaught RuntimeException: Trying to call method getrelationbyalias on a non-object in /tmp/test.php:16
Stack trace:
#0 [internal function]: Phalcon\Mvc\Model->__isset('oldSnapshot')
#1 [internal function]: Phalcon\Mvc\Model\Manager->load('Customer')
#2 [internal function]: Phalcon\Mvc\Model\Query->_prepareSelect()
#3 [internal function]: Phalcon\Mvc\Model\Query->parse()
#4 [internal function]: Phalcon\Mvc\Model\Query->execute()
#5 [internal function]: Phalcon\Mvc\Model::find(Array)
#6 /tmp/test.php(16): Phalcon\Mvc\Model\Criteria->execute()
#7 {main}
  thrown in /tmp/test.php on line 16
```

1. Trying to call method on a non-object it isn't user error. We shouldn't call methods on a non-objects
2. I did not find any documentation that step by step showed how to initialize the connection using Phalcon Adapters. Theoretically documentations is exists. But I could not find. This is a problem
3. The pieces of related documentation I managed to find (incomplete) do not say anything about `getrelationbyalias` and so on

```
php -d extension=ext/modules/phalcon.so --ri phalcon

phalcon


Phalcon is a full stack PHP framework, delivered as a PHP extension, offering lower resource consumption and high performance.
phalcon => enabled
Author => Phalcon Team and contributors
Version => 4.0.5
Build Date => Apr 30 2020 22:49:31
Powered by Zephir => Version 0.12.18-26d47456

Directive => Local Value => Master Value
phalcon.db.escape_identifiers => On => On
phalcon.db.force_casting => Off => Off
phalcon.orm.case_insensitive_column_map => Off => Off
phalcon.orm.cast_last_insert_id_to_int => Off => Off
phalcon.orm.cast_on_hydrate => Off => Off
phalcon.orm.column_renaming => On => On
phalcon.orm.disable_assign_setters => Off => Off
phalcon.orm.enable_implicit_joins => On => On
phalcon.orm.enable_literals => On => On
phalcon.orm.events => On => On
phalcon.orm.exception_on_failed_save => Off => Off
phalcon.orm.exception_on_failed_metadata_save => On => On
phalcon.orm.ignore_unknown_columns => Off => Off
phalcon.orm.late_state_binding => Off => Off
phalcon.orm.not_null_validations => On => On
phalcon.orm.update_snapshot_on_save => On => On
phalcon.orm.virtual_foreign_keys => On => On
phalcon.warning.enable => On => On
```

**Comment by sergeyklay** [comment]
```php
use Phalcon\Di;
use Phalcon\Di\FactoryDefault;
use Phalcon\Mvc\Model;

Di::setDefault(new FactoryDefault());

class Customer extends Model {}

var_dump(new Customer);
```


```
PHP Fatal error:  Uncaught RuntimeException: Trying to call method getrelationbyalias on a non-object in /tmp/test.php:6
Stack trace:
#0 /tmp/test.php(6): Phalcon\Mvc\Model->__isset('oldSnapshot')
#1 {main}
  thrown in /tmp/test.php on line 6

Fatal error: Uncaught RuntimeException: Trying to call method getrelationbyalias on a non-object in /tmp/test.php:6
Stack trace:
#0 /tmp/test.php(6): Phalcon\Mvc\Model->__isset('oldSnapshot')
#1 {main}
  thrown in /tmp/test.php on line 6

```

**Comment by guweigang** [comment]
hey, after upgrade to zephir 0.12.18 and rebuild my extension,,, i met the same problem

Firstly, It can not read class-property with empty array initializer
```zephir
protected finalizers = []
```
It can not get that property, and so go to magic method `__get()`
```
[13-May-2020 00:19:07 Asia/Shanghai] PHP Fatal error:  Uncaught Phalcon\Di\Exception: A dependency injection object is required to access the application services in phalcon/di/injectable.zep:127
Stack trace:
#0 [internal function]: Phalcon\Di\Injectable->__get('finalizers')
#1 /Users/guweigang/wwwroot/nginx-unit/wealth-api/common/bin/fp-devtool(6): PhalconPlus\Bootstrap->__construct('/Users/guweigan...')
#2 {main}
  thrown in phalcon/di/injectable.zep on line 127
```
So, I put the initializer in constructor and it works. So I start my application, open login page, fill in some data, submit the form,  and I met exactly this problem:
```
[2020-05-12 23:00:14][Nil:Nil][e4ffbc67629c7b7992][ERROR] RuntimeException: Trying to call method getrelationbyalias on a non-object in /Users/guweigang/wwwroot/nginx-unit/wealth-api/uc/app/auth/User.php:93
Stack trace:
#0 [internal function]: Phalcon\Mvc\Model->__isset('__uniqueKeys')
#1 [internal function]: Phalcon\Mvc\Model\Manager->load('LightCloud\\Uc\\M...', true)
#2 [internal function]: Phalcon\Mvc\Model\Query->_prepareSelect()
#3 [internal function]: Phalcon\Mvc\Model\Query->parse()
#4 [internal function]: Phalcon\Mvc\Model\Query->execute()
```
My PHP version:
```
PHP 7.2.30 (cli) (built: Apr 23 2020 02:40:39) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Xdebug v2.9.1, Copyright (c) 2002-2020, by Derick Rethans
    with Zend OPcache v7.2.30, Copyright (c) 1999-2018, by Zend Technologies
```

So there exists bugs with Zephir 0.12.18 ?

**Comment by sergeyklay** [comment]
@guweigang Could you please try 0.12.17? I'm not pretty sure, but it seems it bug related to 0.12.18 version. I'll release bug fix ASAP

**Comment by guweigang** [comment]
0.12.17 is ok for me

**Comment by sergeyklay** [comment]
@guweigang Could you try 0.12.19?

**Comment by guweigang** [comment]
@sergeyklay Tried it, No problems now. Thank you :)
