### ISSUE TITLE
[BUG]: Uncaught TypeError: Phalcon\Db\Adapter\Pdo\AbstractPdo::query(): Argument #2 ($bindParams) must be of type array, null given

### ISSUE THREAD

**Issue by zordon13** [phalcon/cphalcon#15368]
**Describe the bug**
```
PHP Fatal error:  Uncaught TypeError: Phalcon\Db\Adapter\Pdo\AbstractPdo::query(): Argument #2 ($bindParams) must be of type array, null given in /var/wd/project/src/app/modules/cli/tasks/TestTask.php:27
Stack trace:
#0 [internal function]: Phalcon\Db\Adapter\Pdo\AbstractPdo->query()
#1 /var/wd/project/src/app/modules/cli/tasks/TestTask.php(27): Phalcon\Db\Adapter\AbstractAdapter->fetchAll()
#2 [internal function]: TestTask->mainAction()
#3 [internal function]: Phalcon\Cli\Dispatcher->callActionMethod()
#4 [internal function]: Phalcon\Dispatcher\AbstractDispatcher->dispatch()
#5 /var/wd/project/src/app/cli.php(68): Phalcon\Cli\Console->handle()
#6 {main}
  thrown in /var/wd/project/src/app/modules/cli/tasks/TestTask.php on line 27
```

> Provide minimal script to reproduce the issue

```php
$this->db->fetchAll('select 1+1');

```

**Details**
 - Phalcon version: 	4.1.0
 - PHP Version:  PHP 8.0.3 (cli) (built: Mar 31 2021 23:09:52) ( NTS )
 - Operating System: gentoo
 - Installation type: Compiling from source
 - Zephir version (if any):
 - Server: Nginx 
 - Other related info (Database, table schema): Postgresql 12.3

**Comment by zordon13** [comment]
```
 php --ri phalcon    

phalcon


Phalcon is a full stack PHP framework, delivered as a PHP extension, offering lower resource consumption and high performance.
phalcon => enabled
Author => Phalcon Team and contributors
Version => 4.1.0
Build Date => Apr  2 2021 23:52:30
Powered by Zephir => Version 0.12.20-f6197948

Directive => Local Value => Master Value
phalcon.db.escape_identifiers => On => On
phalcon.db.force_casting => Off => Off
phalcon.orm.case_insensitive_column_map => Off => Off
phalcon.orm.cast_last_insert_id_to_int => Off => Off
phalcon.orm.cast_on_hydrate => Off => Off
phalcon.orm.column_renaming => On => On
phalcon.orm.disable_assign_setters => Off => Off
phalcon.orm.enable_implicit_joins => On => On
phalcon.orm.enable_literals => On => On
phalcon.orm.events => On => On
phalcon.orm.exception_on_failed_save => Off => Off
phalcon.orm.exception_on_failed_metadata_save => On => On
phalcon.orm.ignore_unknown_columns => Off => Off
phalcon.orm.late_state_binding => Off => Off
phalcon.orm.not_null_validations => On => On
phalcon.orm.update_snapshot_on_save => On => On
phalcon.orm.virtual_foreign_keys => Off => Off
phalcon.warning.enable => On => On
dutd@dzdm-dev-host ~/workspace/dzdm $ 

```
```
php --version
PHP 8.0.3 (cli) (built: Mar 31 2021 23:09:52) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.3, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.3, Copyright (c), by Zend Technologies
    with Xdebug v3.0.3, Copyright (c) 2002-2021, by Derick Rethans
```

**Comment by zordon13** [comment]
Build from cphalcon-5.0.x branch

**Comment by Izopi4a** [comment]
i am unable to reproduce this. 

this looks odd:

```
Version => 4.1.0
Build Date => Apr  2 2021 23:52:30
Powered by Zephir => Version 0.12.20-f6197948
```

for me it is:

```
Phalcon is a full stack PHP framework, delivered as a PHP extension, offering lower resource consumption and high performance.
phalcon => enabled
Author => Phalcon Team and contributors
Version => 5.0.0-alpha.1
Build Date => Apr  5 2021 05:55:38
Powered by Zephir => Version 0.13.0-d89a471

Directive => Local Value => Master Value
phalcon.db.escape_identifiers => On => On
phalcon.db.force_casting => Off => Off
phalcon.orm.case_insensitive_column_map => Off => Off
phalcon.orm.cast_last_insert_id_to_int => Off => Off
phalcon.orm.cast_on_hydrate => Off => Off
phalcon.orm.column_renaming => On => On
phalcon.orm.disable_assign_setters => Off => Off
phalcon.orm.enable_implicit_joins => On => On
phalcon.orm.enable_literals => On => On
phalcon.orm.events => On => On
phalcon.orm.exception_on_failed_save => Off => Off
phalcon.orm.exception_on_failed_metadata_save => On => On
phalcon.orm.ignore_unknown_columns => Off => Off
phalcon.orm.late_state_binding => Off => Off
phalcon.orm.not_null_validations => On => On
phalcon.orm.update_snapshot_on_save => On => On
phalcon.orm.virtual_foreign_keys => On => On
phalcon.warning.enable => On => On
```

can you use the latest zephir, make sure you are at 5.0.x branch and you isntall the correct extension, fpm restart etc... ?

**Comment by zordon13** [comment]
>  Version => 4.1.0
Yes, yes, I thought that the developers did not change the version. My fault

I can't build from 5.0.x branch:

/usr/src/php/cphalcon-5.0.0-alpha.1/build # LC_ALL=en_US.UTF8 ./install
...
In file included from /usr/lib64/php8.0/include/php/Zend/zend_types.h:25,
                 from /usr/lib64/php8.0/include/php/Zend/zend.h:27,
                 from /usr/lib64/php8.0/include/php/main/php.h:31,
                 from /usr/src/php/cphalcon-5.0.0-alpha.1/build/php7/64bits/phalcon.zep.c:46:
/usr/src/php/cphalcon-5.0.0-alpha.1/build/php7/64bits/phalcon.zep.c: In function ‘zim_Phalcon_Html_Link_EvolvableLinkProvider_withLink’:
/usr/src/php/cphalcon-5.0.0-alpha.1/build/php7/64bits/phalcon.zep.c:222225:33: error: ‘PsrLinkLinkInterface_ce_ptr’ undeclared (first use in this function)
222225 |   Z_PARAM_OBJECT_OF_CLASS(link, PsrLinkLinkInterface_ce_ptr)
... 
/usr/src/php/cphalcon-5.0.0-alpha.1/build/php7/64bits/phalcon.zep.c: In function ‘zim_Phalcon_Html_Link_EvolvableLinkProvider_withoutLink’:
/usr/src/php/cphalcon-5.0.0-alpha.1/build/php7/64bits/phalcon.zep.c:222262:33: error: ‘PsrLinkLinkInterface_ce_ptr’ undeclared (first use in this function)
222262 |   Z_PARAM_OBJECT_OF_CLASS(link, PsrLinkLinkInterface_ce_ptr)
       |                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/lib64/php8.0/include/php/Zend/zend_portability.h:325:52: note: in definition of macro ‘UNEXPECTED’

...
/usr/src/php/cphalcon-5.0.0-alpha.1/build/php7/64bits/phalcon.zep.c: In function ‘zim_Phalcon_Html_Link_LinkProvider_getKey’:
/usr/src/php/cphalcon-5.0.0-alpha.1/build/php7/64bits/phalcon.zep.c:222678:33: error: ‘PsrLinkLinkInterface_ce_ptr’ undeclared (first use in this function)
222678 |   Z_PARAM_OBJECT_OF_CLASS(link, PsrLinkLinkInterface_ce_ptr)
       |                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/lib64/php8.0/include/php/Zend/zend_portability.h:325:52: note: in definition of macro ‘UNEXPECTED’

gcc:            9.3.0-r2::gentoo
libtool:        2.4.6-r6::gentoo
glibc:           2.32-r7::gentoo

**Comment by zordon13** [comment]
Install script select php7 folder, but
php --version
PHP 8.0.3 (cli) (built: Apr  1 2021 13:09:04) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.3, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.3, Copyright (c), by Zend Technologies
    with Xdebug v3.0.3, Copyright (c) 2002-2021, by Derick Rethans

**Comment by Jeckerson** [comment]
@zordon13 You need to install psr extension first in order to phalcon could pick its headers and compile.

**Comment by zordon13** [comment]
Manually  build from build/php8/64bits/ using:

```
/usr/lib64/php8.0/bin/phpize
autoreconf
aclocal
autoconf --force
autoheader
libtoolize
./configure
make
make install
```
```
Installing shared extensions:     /usr/lib64/php8.0/lib/extensions/no-debug-non-zts-20200930/
Installing header files:          /usr/lib64/php8.0/include/php/
```
```
cat /etc/php/cli-php8.0/ext-active/phalcon.ini                                              
phalcon.orm.virtual_foreign_keys = Off
extension=phalcon.so
```
```
php --ri phalcon                                                                       

phalcon
...
Version => 4.1.0
Build Date => Apr  5 2021 20:33:34
Powered by Zephir => Version 0.12.20-f6197948
```
Don't understand why version not change.I build from cphalcon-5.0.0-alpha.1 
from https://github.com/phalcon/cphalcon/archive/refs/tags/v5.0.0-alpha.1.tar.gz

**Comment by Izopi4a** [comment]
perhaps php.ini for cli is dirrent, you can check with

```
 php -i | grep php.ini
```

**Comment by zordon13** [comment]
> @zordon13 You need to install psr extension first in order to phalcon could pick its headers and compile.

```
php --ri psr         

psr

Version => 0.7.0
Released => 2019-08-12
Authors => John Boehr <jbboehr@gmail.com> (lead)
PSR-3 Log Version => 1.0.0
PSR-6 Cache Version => 1.0.0
PSR-7 Http Message Version => 1.0.0
PSR-11 Container Version => 1.0.0
PSR-13 Link Version => 1.0.0
PSR-14 Event Dispatcher => 1.0.0
PSR-15 HTTP Handlers (Server Handler) => 1.0.0
PSR-15 HTTP Handlers (Middleware) => 1.0.0
PSR-16 Simple Cache Version => 1.0.0
PSR-17 HTTP Factories => 1.0.0
PSR-18 HTTP Client => 1.0.0

```
same error:
```
/usr/src/php/cphalcon-5.0.0-alpha.1/build/php7/64bits/phalcon.zep.c:222678:33: ошибка: «PsrLinkLinkInterface_ce_ptr» не описан (первое использование в этой функции)
222678 |   Z_PARAM_OBJECT_OF_CLASS(link, PsrLinkLinkInterface_ce_ptr)
       |                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~
```

update psr from git
```
php --ri psr

psr

Version => 1.0.1
Released => 2020-11-12
Authors => John Boehr <jbboehr@gmail.com> (lead)
PSR-3 Log Version => 1.0.0
PSR-6 Cache Version => 1.0.0
PSR-7 Http Message Version => 1.0.0
PSR-11 Container Version => 1.1.1
PSR-13 Link Version => 1.0.0
PSR-14 Event Dispatcher => 1.0.0
PSR-15 HTTP Handlers (Server Handler) => 1.0.0
PSR-15 HTTP Handlers (Middleware) => 1.0.0
PSR-16 Simple Cache Version => 1.0.0
PSR-17 HTTP Factories => 1.0.0
PSR-18 HTTP Client => 1.0.0
```
same error:
```
/usr/src/php/cphalcon-5.0.0-alpha.1/build/php7/64bits/phalcon.zep.c:222225:33: ошибка: «PsrLinkLinkInterface_ce_ptr» не описан (первое использование в этой функции)
222225 |   Z_PARAM_OBJECT_OF_CLASS(link, PsrLinkLinkInterface_ce_ptr)
```

**Comment by zordon13** [comment]
>  php -i | grep php.ini

```
php -i | grep php.ini
Configuration File (php.ini) Path => /etc/php/cli-php8.0
Loaded Configuration File => /etc/php/cli-php8.0/php.ini

```



> php -d /usr/lib64/php8.0/lib/extensions/no-debug-non-zts-20200930/phalcon.so --ri phalcon

```
php -d /usr/lib64/php8.0/lib/extensions/no-debug-non-zts-20200930/phalcon.so --ri phalcon

phalcon


Phalcon is a full stack PHP framework, delivered as a PHP extension, offering lower resource consumption and high performance.
phalcon => enabled
Author => Phalcon Team and contributors
Version => 4.1.0
Build Date => Apr  5 2021 20:54:04
Powered by Zephir => Version 0.12.20-f6197948

Directive => Local Value => Master Value
phalcon.db.escape_identifiers => On => On
phalcon.db.force_casting => Off => Off
phalcon.orm.case_insensitive_column_map => Off => Off
phalcon.orm.cast_last_insert_id_to_int => Off => Off
phalcon.orm.cast_on_hydrate => Off => Off
phalcon.orm.column_renaming => On => On
phalcon.orm.disable_assign_setters => Off => Off
phalcon.orm.enable_implicit_joins => On => On
phalcon.orm.enable_literals => On => On
phalcon.orm.events => On => On
phalcon.orm.exception_on_failed_save => Off => Off
phalcon.orm.exception_on_failed_metadata_save => On => On
phalcon.orm.ignore_unknown_columns => Off => Off
phalcon.orm.late_state_binding => Off => Off
phalcon.orm.not_null_validations => On => On
phalcon.orm.update_snapshot_on_save => On => On
phalcon.orm.virtual_foreign_keys => Off => Off
phalcon.warning.enable => On => On
```

**Comment by Izopi4a** [comment]
can you ping me on discord please, so we can resolve the build, seems like something simple. @ izo https://phalcon.io/discord

**Comment by Jeckerson** [comment]
@zordon13 

> Powered by Zephir => Version 0.12.20-f6197948

Must be `0.13.x`

**Comment by zordon13** [comment]
Thank to @Izopi4a
build lastest zephir-parser from source
download zephir.phar from 0.13.1 release to phalcon/ext
php  zephir.phar clean &&  php  zephir.phar generate 
build phalcon
now:
Version => 5.0.0-alpha.1
Build Date => Apr  5 2021 23:58:37
Powered by Zephir => Version 0.13.0-99f0e65

Error from subj not reproduce.
Now db->fetchAll work
