### ISSUE TITLE
[BUG]: Model::find - Invalid parameter number 

### ISSUE THREAD

**Issue by sinbadxiii** [phalcon/cphalcon#15810]
Hi,

after updating to Phalcon alpha7, the following behavior of the model broke:

```php
$query = $this->request->get('term');

  $result = Model::find([
      'id = :query: OR name = :query:',
      'bind' => [
          'query' => $query
      ]
  ]);
```

```
SQLSTATE[HY093]: Invalid parameter number
#0 [internal function]: PDOStatement->execute()
#1 [internal function]: Phalcon\Db\Adapter\Pdo\AbstractPdo->executePrepared()
#2 [internal function]: Phalcon\Db\Adapter\Pdo\AbstractPdo->query()
#3 [internal function]: Phalcon\Mvc\Model\Query->executeSelect()
#4 [internal function]: Phalcon\Mvc\Model\Query->execute()
#5 Phalcon\Mvc\Model::find()
#6 [internal function]: App\Crm\Controllers\BrandsController->getListAction()
#7 [internal function]: Phalcon\Dispatcher\AbstractDispatcher->callActionMethod()
#8 [internal function]: Phalcon\Dispatcher\AbstractDispatcher->dispatch()
#9 Application.php(62): Phalcon\Mvc\Application->handle()
#10 public/index.php(34): App\Application->run()
#11 {main}
```

if you correct the code for this, it works:

```php
$result = Model::find([
      'id = :query: OR name = :query2:',
      'bind' => [
          'query' => $query,
          'query2' => $query,
      ]
  ]);
```

**Details**
 - Phalcon version: Phalcon 5.0.0alpha7
 - PHP Version: Php 8.0.13
 - Operating System: Linux Mint 20.2
 - Installation type: Compiling from source
 - Zephir version (if any): 0.15.1
 - Server: Nginx
 - MySql 8

**Comment by Jeckerson** [comment]
This might not be bug, but a feature, because for each bind parameter you need unique key, it won't make mass replace. Also, this behaviour exists since always.

**Comment by sinbadxiii** [comment]
It was https://github.com/phalcon/cphalcon/commit/1501a381d49cabf0718cccc389680f7bea02eb01#diff-e1a98cdab02c44ebe6d6e0167bce1125e68798dc7890403032791ba4b669e85eR75

as a solution config/database:

 ```php
'database' => [
       'adapter'     => $_ENV['DB_CONNECTION'],
       'host'        => $_ENV['DB_HOST'],
       'username'    => $_ENV['DB_USERNAME'],
       'password'    => $_ENV['DB_PASSWORD'],
       'dbname'      => $_ENV['DB_DATABASE'],
       'charset'     => $_ENV['DB_CHARSET'],
       'options' => [
           \PDO::ATTR_EMULATE_PREPARES => true
       ]
],
```
