### ISSUE TITLE
[BUG]: `SoftDelete` behavior tries to create new record of `belongsTo` relationship

### ISSUE THREAD

**Issue by bazsa001** [phalcon/cphalcon#16453]
**Describe the bug**

When trying to delete a model record with `SoftDelete` behavior enabled on the model, Phalcon attempts to re-create another model record that the deleted record `belongsTo`.

**To Reproduce**
1. Define two models (`Foo` and `Bar`);
2. Define a property on `Foo` and validate it using `Validator\Uniqueness`;
3. Define a one-to-many relationship between `Foo` and `Bar`:
- in `Foo::initialize()`: `$this->hasMany('id', 'Bar', 'foo_id', ["alias" => "Bars"]);`
- in `Bar::initialize()`: `$this->belongsTo('foo_id', 'Foo', 'id');`
4. Define the built-in `SoftDelete` behavior for `Bar` using the field `Bar::deleted`;
5. Create one record of `Foo` and save it, then create one record of `Bar` with `foo_id` refering to the recently created `Foo` record and save it;
6. Try to delete the `Bar` record using its `delete()` method.

During the deletion process, the uniqueness validator of `Foo` fails, as Phalcon is trying to create a new record of a model using the data of the already existing record. It's not evident to me why Phalcon wants to touch any related records at all during soft delete, but here's the output of `debug_print_backtrace()` as called from `Foo::validation()`:

```
#0 [internal function]: Foo->validation()
#1 [internal function]: Phalcon\Mvc\Model->fireEventCancel('validation')
#2 [internal function]: Phalcon\Mvc\Model->preSave(Object(Phalcon\Mvc\Model\MetaData\Memory), false, 'id')
#3 [internal function]: Phalcon\Mvc\Model->save()
#4 [internal function]: Phalcon\Mvc\Model->preSaveRelatedRecords(Object(Phalcon\Db\Adapter\Pdo\Mysql), Array)
#5 [internal function]: Phalcon\Mvc\Model->save()
#6 [internal function]: Phalcon\Mvc\Model\Behavior\SoftDelete->notify('beforeDelete', Object(Bar))
#7 [internal function]: Phalcon\Mvc\Model\Manager->notifyEvent('beforeDelete', Object(Bar))
#8 [internal function]: Phalcon\Mvc\Model->fireEventCancel('beforeDelete')
#9 /srv/app/controllers/BarController.php(806): Phalcon\Mvc\Model->delete()
#10 [internal function]: BarController->deleteAction()
#11 [internal function]: Phalcon\Dispatcher\AbstractDispatcher->callActionMethod(Object(BarController), 'deleteAction', Array)
#12 [internal function]: Phalcon\Dispatcher\AbstractDispatcher->dispatch() #13 /srv/public/index.php(33): Phalcon\Mvc\Application->handle('/bar/delet...')
```

Calling the `save()` method of the `Bar` instance directly does not produce this issue.

**Expected behavior**
I would not expect related records to be re-saved during a soft delete, but even if they do get re-saved, it should be an update operation, not a create operation.

**Details**
 - Phalcon version: 5.3.1
 - PHP Version: 8.1
 - Operating System: Ubuntu
 - Installation type: Compiled from source
 - Server: Nginx
 - Other related info (Database, table schema): MySQL

**Additional context**

**Comment by niden** [comment]
Resolved in https://github.com/phalcon/cphalcon/pull/16916

Thank you @bazsa001
