### ISSUE TITLE
[BUG]: 5.3.1 to 5.4.0:  Phalcon\Mvc\Router\Exception: A dependency injection container is required to access the 'request' service

### ISSUE THREAD

**Issue by fichtner** [phalcon/cphalcon#16460]
**Describe the bug**
Exception after updating from 5.3.1 to 5.4.0:

```
[28-Oct-2023 10:34:51 Europe/Berlin] Phalcon\Mvc\Router\Exception: A dependency injection container is required to access the 'request' service in phalcon/Mvc/Router.zep:724
Stack trace:
#0 /usr/local/opnsense/mvc/app/config/services_api.php(92): Phalcon\Mvc\Router->handle('/api/routes/gat...')
#1 [internal function]: Closure->{closure}()
#2 [internal function]: Phalcon\Di\Service->resolve(NULL, Object(Phalcon\Di\FactoryDefault))
#3 [internal function]: Phalcon\Di\Di->get('router', NULL)
#4 [internal function]: Phalcon\Di\Di->getShared('router')
#5 /usr/local/opnsense/www/api.php(24): Phalcon\Mvc\Application->handle('/api/routes/gat...')
#6 {main}
```

**To Reproduce**

Our code in question has been working through multiple Phalcon major versions here. Code in question:

https://github.com/opnsense/core/blob/d560e84934d5f00a3dfa10245fd3853a3f7e6ab3/src/opnsense/mvc/app/config/services_api.php#L90L94

**Expected behavior**

Act like 5.3.x ideally. Could be something we handled wrong here forever though.

**Screenshots**

N/A

**Details**

5.4.0

 - Phalcon version: 5.4.0
 - PHP Version: 8.2.11
 - Operating System: FreeBSD 13.2
 - Installation type: package manager (test build)
 - Server: Lighttpd

**Additional context**

N/A

**Comment by niden** [comment]
@fichtner I did a diff between 5.3.1 and 5.4.0 and did not see any changes in the router or anything else that might be indicative of why you see this error. 

In the Router code the check is this:

```
        let container = <DiInterface> this->container;
        if container === null {
            throw new Exception(
                "A dependency injection container is required to access the 'request' service"
            );
        }
```

so Phalcon sees that the container is `null`. 

If you want ping me in discord to try and diagnose this further, since I will need help to set opnsense up on my local to debug.

**Comment by fichtner** [comment]
Thanks for taking a closer look. Let me see if I can reproduce this with a clean build on Monday and let you have a simple script that triggers this too before proceeding.


Cheers,
Franco

**Comment by fichtner** [comment]
I had some spare time: clean compile and issue still exists. Also glanced over the diff on your end but came up empty as well. `FactoryDefault` works the same before and after, but the router attach is being weird. I'll find you on Monday, maybe you have ideas how to approach this. I could also do a bisect on the changes perhaps.


Cheers,
Franco

**Comment by fichtner** [comment]
Still the case on 5.6.1. Can we pick this back up? I reckon it might be more of an application issue, but still sort of a regression that I can't wrap my head around.


Cheers,
Franco

**Comment by fichtner** [comment]
I followed similar reports and ended up "fixing" it with https://github.com/opnsense/core/commit/5f855524e -- for me it's ok to close but I'd like someone to look if that was intended... :)

**Comment by zoechi** [comment]
@fichtner it was the only search result. Sorry for not providing more information.
I was able to update OPNSense using ssh and now it's working again.

**Comment by fichtner** [comment]
Was probably in an intermittent update state with newer Phalcon package and older core package. All patched to 24.1.2 should get rid of the error for good indeed. 😊

**Comment by niden** [comment]
@fichtner Is this still an issue (without your fix) or have you not tried it? Curious issue though because the router does extend `AbstractInjectionAware`

PS: Apologies for the very long time to respond.

**Comment by niden** [comment]
I am going to close this one. I assume it is not an issue anymore. If it resurfaces, please open a new issue (I promise not to wait for years to address it). :)

**Comment by fichtner** [comment]
@niden Sorry for the delay. Haven't seen this again since reshuffling the code with https://github.com/opnsense/core/commit/1fd6689f6d1d513e12f11d69f60277c9b92bda13 so safe to close indeed. :)

**Comment by niden** [comment]
@fichtner happy to hear that. Again apologies for the very late resolution to this. Hopefully now that we got the bugs down to a more manageable number we will be able to respond faster to issues.

**Comment by fichtner** [comment]
@niden no worries. Nice to see more releases these days from you. Keep it up ❤️
