### ISSUE TITLE
[BUG]:  phalcon devtools not working 

### ISSUE THREAD

**Issue by aaronkingdom** [phalcon/cphalcon#16569]
Questions? Forum: https://phalcon.io/forum or Discord: https://phalcon.io/discord

**Describe the bug**
 phalcon devtools not working （phlcon5.6+php8.3）

**To Reproduce**
> Provide output if related. Provide coredump if any. Use https://docs.phalcon.io/latest/generating-backtrace as reference.

**Screenshots**

**Details**
 - Phalcon version: 5.6
 - PHP Version: 8.3
 - Operating System: ubuntu
 - Installation type: Compiling from source
 - Zephir version (if any):
 - Server: Nginx 
 - Other related info (Database, table schema):

**Additional context**
**Compiling：**
For PHP 8.+ the above paths might differ slightly.

The instructions above will compile and install the module on your system. You can also compile the extension and then add it manually in your ini file:
cd cphalcon/
git checkout tags/v5.6.0 ./
cd ext
phpize
./configure
make && make install

**php --ri phalcon**

phalcon
Phalcon is a full stack PHP framework, delivered as a PHP extension, offering lower resource consumption and high performance.
phalcon => enabled
Author => Phalcon Team and contributors
Version => 5.6.0
Build Date => Apr 13 2024 21:28:36
Powered by Zephir => Version 0.18.0-$Id$

Directive => Local Value => Master Value
phalcon.db.escape_identifiers => On => On
phalcon.db.force_casting => Off => Off
phalcon.orm.case_insensitive_column_map => Off => Off
phalcon.orm.cast_last_insert_id_to_int => Off => Off
phalcon.orm.cast_on_hydrate => Off => Off
phalcon.orm.column_renaming => On => On
phalcon.orm.disable_assign_setters => Off => Off
phalcon.orm.enable_implicit_joins => On => On
phalcon.orm.enable_literals => On => On
phalcon.orm.events => On => On
phalcon.orm.exception_on_failed_save => Off => Off
phalcon.orm.exception_on_failed_metadata_save => On => On
phalcon.orm.ignore_unknown_columns => Off => Off
phalcon.orm.late_state_binding => Off => Off
phalcon.orm.not_null_validations => On => On
phalcon.orm.resultset_prefetch_records => 0 => 0
phalcon.orm.update_snapshot_on_save => On => On
phalcon.orm.virtual_foreign_keys => On => On
phalcon.orm.dynamic_update => On => On
phalcon.warning.enable => On => On

**composer require phalcon/devtools**
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Continue as root/super user [yes]? yes
./composer.json has been created
Running composer update phalcon/devtools
Loading composer repositories with package information
Updating dependencies
Lock file operations: 20 installs, 0 updates, 0 removals
  - Locking graham-campbell/result-type (v1.1.2)
  - Locking nette/php-generator (v3.5.4)
  - Locking nette/utils (v3.2.10)
  - Locking nikic/php-parser (v4.19.1)
  - Locking phalcon/cli-options-parser (v1.3.0)
  - Locking phalcon/devtools (v4.2.0)
  - Locking phalcon/migrations (v2.2.4)
  - Locking phpoption/phpoption (1.9.2)
  - Locking psr/container (2.0.2)
  - Locking psy/psysh (v0.12.3)
  - Locking symfony/console (v7.0.6)
  - Locking symfony/polyfill-ctype (v1.29.0)
  - Locking symfony/polyfill-intl-grapheme (v1.29.0)
  - Locking symfony/polyfill-intl-normalizer (v1.29.0)
  - Locking symfony/polyfill-mbstring (v1.29.0)
  - Locking symfony/polyfill-php80 (v1.29.0)
  - Locking symfony/service-contracts (v3.4.2)
  - Locking symfony/string (v7.0.4)
  - Locking symfony/var-dumper (v7.0.6)
  - Locking vlucas/phpdotenv (v5.6.0)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 20 installs, 0 updates, 0 removals
  - Installing nette/utils (v3.2.10): Extracting archive
  - Installing symfony/polyfill-php80 (v1.29.0): Extracting archive
  - Installing symfony/polyfill-mbstring (v1.29.0): Extracting archive
  - Installing symfony/polyfill-ctype (v1.29.0): Extracting archive
  - Installing phpoption/phpoption (1.9.2): Extracting archive
  - Installing graham-campbell/result-type (v1.1.2): Extracting archive
  - Installing vlucas/phpdotenv (v5.6.0): Extracting archive
  - Installing symfony/var-dumper (v7.0.6): Extracting archive
  - Installing symfony/polyfill-intl-normalizer (v1.29.0): Extracting archive
  - Installing symfony/polyfill-intl-grapheme (v1.29.0): Extracting archive
  - Installing symfony/string (v7.0.4): Extracting archive
  - Installing psr/container (2.0.2): Extracting archive
  - Installing symfony/service-contracts (v3.4.2): Extracting archive
  - Installing symfony/console (v7.0.6): Extracting archive
  - Installing nikic/php-parser (v4.19.1): Extracting archive
  - Installing psy/psysh (v0.12.3): Extracting archive
  - Installing phalcon/cli-options-parser (v1.3.0): Extracting archive
  - Installing nette/php-generator (v3.5.4): Extracting archive
  - Installing phalcon/migrations (v2.2.4): Extracting archive
  - Installing phalcon/devtools (v4.2.0): Extracting archive
2 package suggestions were added by new dependencies, use `composer suggest` to see details.
Generating autoload files
15 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
No security vulnerability advisories found.
Using version ^4.2 for phalcon/devtools
root@Hanxin:/www/wwwroot/test.com# ls
composer.json  composer.lock  vendor

**/www/wwwroot/test.com# phalcon project app**

Phalcon DevTools (4.2.0)

PHP Fatal error:  Uncaught Error: Class "Phalcon\Config" not found in /www/wwwroot/test.com/vendor/phalcon/devtools/src/Builder/Component/AbstractComponent.php:48
Stack trace:
#0 /www/wwwroot/test.com/vendor/phalcon/devtools/src/Commands/Builtin/Project.php(66): Phalcon\DevTools\Builder\Component\AbstractComponent->__construct()
#1 /www/wwwroot/test.com/vendor/phalcon/devtools/src/Script.php(109): Phalcon\DevTools\Commands\Builtin\Project->run()
#2 /www/wwwroot/test.com/vendor/phalcon/devtools/src/Script.php(148): Phalcon\DevTools\Script->dispatch()
#3 /www/wwwroot/test.com/vendor/phalcon/devtools/phalcon(65): Phalcon\DevTools\Script->run()
#4 {main}
  thrown in /www/wwwroot/test.com/vendor/phalcon/devtools/src/Builder/Component/AbstractComponent.php on line 48

Fatal error: Uncaught Error: Class "Phalcon\Config" not found in /www/wwwroot/test.com/vendor/phalcon/devtools/src/Builder/Component/AbstractComponent.php:48
Stack trace:
#0 /www/wwwroot/test.com/vendor/phalcon/devtools/src/Commands/Builtin/Project.php(66): Phalcon\DevTools\Builder\Component\AbstractComponent->__construct()
#1 /www/wwwroot/test.com/vendor/phalcon/devtools/src/Script.php(109): Phalcon\DevTools\Commands\Builtin\Project->run()
#2 /www/wwwroot/test.com/vendor/phalcon/devtools/src/Script.php(148): Phalcon\DevTools\Script->dispatch()
#3 /www/wwwroot/test.com/vendor/phalcon/devtools/phalcon(65): Phalcon\DevTools\Script->run()
#4 {main}
  thrown in /www/wwwroot/test.com/vendor/phalcon/devtools/src/Builder/Component/AbstractComponent.php on line 48

**root@:~# php -m**
[PHP Modules]
bcmath
Core
ctype
curl
date
dom
fileinfo
filter
ftp
gd
gettext
hash
iconv
intl
json
libxml
mbstring
memcached
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
pdo_sqlite
phalcon
Phar
posix
random
Reflection
session
shmop
SimpleXML
soap
sockets
sodium
SPL
sqlite3
standard
sysvsem
tokenizer
xml
xmlreader
xmlwriter
zip
zlib

[Zend Modules]

**Comment by aaronkingdom** [comment]
**Help help help,   Bosses!!

Uncaught Error: Class "Phalcon\Config" not found**

**Comment by kenyeung826** [comment]
phalcon 5.6, use devtools 5.0.0?

Phalcon\Config seems the old path of phalcon version 3 & 4

**Comment by aaronkingdom** [comment]
> phalcon 5.6, use devtools 5.0.0?
> 
> Phalcon\Config seems the old path of phalcon version 3 & 4

ok， thanks,  but i use the news compoer to get phalcon，  the dev tools  newest is 4.2

**Comment by elcreator** [comment]
https://github.com/phalcon/documentation/pull/203/files
